phpvms/phpvms

app/Models/User.php
When updating a user through the users admin, it comes up saying "The email has already been taken." because of the unique rules set in the model. The only time I can think of right at this point to make sure it is unique is on registering, but that's handled by the Validator anyway so this shouldn't be an issue. Unless you're keeping this here for a reason.
=> Remove unique email entry

app/Http/Controllers/Frontend/ProfileController.php, app/Models/User.php, composer.json, composer.lock, config/phpvms.php, resources/views/layouts/default/profile/edit.blade.php, resources/views/layouts/default/profile/fields.blade.php, resources/views/layouts/default/profile/index.blade.php
Added the logic to set avatar to user
=> Avatar Issue

app/Database/migrations/2017_06_07_014930_create_settings_table.php, app/Http/Controllers/Api/FlightController.php, app/Http/Controllers/Frontend/FlightController.php, resources/views/layouts/default/flights/table.blade.php
Pilots now see only their company's flights.
=> flights filtered per va

app/Providers/ExtendedTimezonelistProvider.php, app/Support/TimezonelistExtended.php, config/app.php
Timezone list value is HTML escaped. I have extended the original Timezonelist library to include parameter option to html encode or not.
=> Fix timezone list HTML Escaped

app/Http/Controllers/Frontend/FlightController.php, app/Repositories/SettingRepository.php
- Fixing #263 issue
- Synchronize the query restriction for search function with the initial page load
=> Fix flight search restriction

README.md
It looks like the documentation structure had changed without the README being updated. Both links should now go to the correct page.
=> Fix 404s to requirements/setup in README.md

app/Cron/Nightly/RecalculateStats.php, app/Http/Controllers/Frontend/PirepController.php, app/Listeners/BidEvents.php, app/Models/Rank.php, app/Providers/EventServiceProvider.php, app/Services/FleetService.php, app/Services/PirepService.php, app/Services/UserService.php, tests/PIREPTest.php
Addresses #332
* Fix for PIREP `accept()` call not incrementing user stats
* Moved the bids removal into a listener to decouple it from the accept code directly
=> Fix issue where user stats aren't incremented on PIREP auto accept

app/Contracts/Controller.php, app/Events/BaseEvent.php, app/Http/Controllers/Api/FlightController.php, app/Repositories/FlightRepository.php, modules/Importer/Services/BaseImporter.php, resources/views/admin/flights/search.blade.php, tests/FlightTest.php
Allow the use of `dpt_airport_id` and `arr_airport_id` in the flight search too
=> Flight search for departure/arrival airports not using column names

app/Console/Commands/PirepExport.php
`php artisan phpvms:pirep-export {pirep id} > export.yaml`
Dumps all data related to a PIREP to YAML for debugging/importing somewhere else.
=> Add new command to export a specific PIREP for debugging

app/Models/Pirep.php, app/Repositories/AirportRepository.php, app/Services/GeoService.php, app/Services/ImportExport/FlightImporter.php
If an airport isn't added, PIREP can error out. This makes sure there's at least a default model if it's not found
=> Set a default model value for airports on PIREP

app/Services/ImportExport/AircraftImporter.php, app/Services/ImportExport/AirportImporter.php, app/Services/ImportExport/ExpenseImporter.php, app/Services/ImportExport/FareImporter.php, app/Services/ImportExport/FlightImporter.php, app/Services/ImportExport/SubfleetImporter.php, tests/ImporterTest.php, tests/data/aircraft-update.csv
Using `firstOrNew` instead of `updateOrCreate` when creating/importing the models was causing the rows to not be updated for the 'simple' imports.
=> Importing not updating existing items #486

app/Services/ImportExport/AircraftImporter.php, resources/views/admin/subfleets/table.blade.php, tests/ImporterTest.php
When aircraft are being imported, the subfleet is created on the fly, but the reference to the airline is left out (the DB column is nullable). For now, just attach the first airline. Modify the test to not create the subfleet ahead of time, only an airline.
Also call the airline name, etc using `optional()`
closes  #479
=> New subfleet not being attached to an airline on import #479

app/Database/seeds/permissions.yml, app/Http/Routes/admin.php, config/laratrust.php
Check user permissions on the routes to make sure they have access. 
closes #508
=> Check user permissions on the routes #508

app/helpers.php, public/.htaccess
Can't replicate #511 but did find an issue with error pages not showing if database, etc, isn't setup yet, since it can't find the default theme.
refs #511
=> Error page not showing when database isn't configured

app/Services/Installer/SeederService.php, modules/Installer/Resources/views/flash/message.blade.php, modules/Updater/Http/Controllers/UpdateController.php, resources/views/admin/flash/message.blade.php
Reduce the number of queries used by the update check for the seeds. From `Nsettings * Npermissions` to just two
=> Reduce number of queries for update check

app/Contracts/Migration.php, app/Http/Controllers/Admin/MaintenanceController.php, app/Services/Installer/InstallerService.php, modules/Updater/Http/Controllers/UpdateController.php
Try to clear the view/compiled caches when updating
refs #408
=> Try to clear caches before updating

resources/views/layouts/default/app.blade.php
Add Bootstrap code for showing the hamburger menu for responsive views.
refs #485
=> Add menu bar for mobile

app/Services/GeoService.php, resources/views/admin/flights/show_fields.blade.php, resources/views/admin/flights/table.blade.php, resources/views/layouts/default/airports/show.blade.php, resources/views/layouts/default/flights/show.blade.php, resources/views/layouts/default/flights/table.blade.php
- Use `optional()` around getting airports in case it's an airport that doesn't exist in the local database
- Use `xxx_airport_id` fields in some places to prevent additional lookup queries
=> Use optional() around the airport fields

resources/views/layouts/default/flights/table.blade.php
=> Add logo to the flights page if its set #417

app/Http/Controllers/Admin/SettingsController.php, resources/views/admin/settings/table.blade.php, resources/views/layouts/.gitignore
* Refresh the theme cache when the settings page is loaded
* Fix to the theme on the settings page
* Add `.gitignore` in the `views/layouts` directory
closes #554
=> Refresh theme cache on settings page load #554

app/Http/Routes/web.php, composer.lock
Move the public routes to being below the authenticated routes. Makes sure there's no conflicts
closes #559
=> Route not found error for Pirep::resource() call #559

.travis/deploy_script.sh, app/Console/Commands/Version.php, app/Http/Composers/VersionComposer.php, app/Providers/ComposerServiceProvider.php, app/Services/VersionService.php, config/app.php, config/version.yml, resources/views/admin/app.blade.php, resources/views/admin/sidebar.blade.php
- Fix where pre-release/build metadata tag not being saved
- Cleanup deploy script so it's less confusing where the version is coming from
- View composer to set the proper version ID with pre-release tag in the admin
- Popover to show the full version incl date/build ID string
refs #575
=> Upstream null version; build version tags not being saved properly #575

app/Services/RoleService.php, app/Support/Countries.php, modules/Importer/Services/Importers/GroupImporter.php, modules/Importer/Services/Importers/UserImport.php
- Make sure a user's country is copied over
- Ignore the old "core" groups of active/in-active pilots.
=> User country mapping; ignore unused groups #443 

app/Database/migrations/2020_02_26_044305_modify_airports_coordinates.php, app/Models/Airport.php
- Remove 4 char restriction on ICAO (accept 3 char IDs, custom)
- Change from float to more precise decimal column
closes #590
=> Remove 4 char restriction from ICAO; use decimal type for lat/lon #590

app/Http/Controllers/Api/FlightController.php, app/Http/Resources/Flight.php, resources/views/admin/flights/fields.blade.php
- Return empty flight fields as an object, not array
- Eager loading of the flight relations
Closes #618
=> API: Flight fields are an array when empty #618

app/Database/migrations/2020_03_06_141153_fares_add_type.php, app/Http/Controllers/Admin/FareController.php, app/Http/Controllers/Admin/SubfleetController.php, app/Http/Resources/Fare.php, app/Models/Enums/FareType.php, app/Models/Expense.php, app/Models/Fare.php, app/Services/Finance/PirepFinanceService.php, resources/views/admin/fares/fields.blade.php, resources/views/admin/subfleets/fares.blade.php, resources/views/admin/subfleets/fields.blade.php, resources/views/layouts/default/pireps/fares.blade.php
- Add a `type` specifier for fares
- Add the specifier into views
- No unit conversions
- Change memo to reflect pax/cargo fare
Closes #621
=> Add fare type for pax/cargo/mixed flights #621

app/Contracts/Model.php, app/Database/migrations/2017_06_08_0000_create_users_table.php, app/Database/migrations/2017_12_20_005147_create_acars_tables.php, app/Database/migrations/2018_01_03_014930_create_stats_table.php, app/Database/migrations/2020_03_09_141152_increase_id_lengths.php, app/Support/Utils.php, modules/Importer/Services/Importers/FlightImporter.php
Salting for hash ID wasn't unique enough. Taking this time to increase ID column sizes to 36 chars (UUID) and increase the current hash ID size from 12 to 16. Closes #630
=> Increase ID column size; seed ID generator with uniqid() #630

app/Http/Controllers/Api/UserController.php, app/Http/Resources/User.php, app/Http/Resources/UserBid.php, app/Models/Bid.php, app/Models/User.php, tests/BidTest.php, tests/PIREPTest.php
Don't load bids, but fix response so that it can be loaded and response looks the same as `/api/user/bids`. User flight count not being returned properly in the API
closes #639
=> Don't return bids by default, fix user flight column #639

app/Http/Controllers/Frontend/UserController.php, app/Models/User.php, resources/views/layouts/default/home.blade.php, resources/views/layouts/default/profile/index.blade.php, resources/views/layouts/default/users/table.blade.php, resources/views/layouts/default/widgets/latest_news.blade.php, resources/views/layouts/default/widgets/latest_pilots.blade.php, tests/UserTest.php
- Private version of user name
Close #656
=> Add privatized version of name #656

app/Http/Controllers/Admin/SettingsController.php, app/Models/Traits/JournalTrait.php, app/Repositories/JournalRepository.php, app/Services/Finance/PirepFinanceService.php, app/Services/FinanceService.php, app/Services/Installer/SeederService.php, app/Support/Money.php, config/phpvms.php, resources/stubs/installer/config.stub, resources/views/admin/aircraft/expenses.blade.php, resources/views/admin/airports/expenses.blade.php, resources/views/admin/pireps/transactions.blade.php, resources/views/admin/settings/table.blade.php, resources/views/admin/subfleets/expenses.blade.php, tests/FinanceTest.php
Move the currency setting from `config()` to `setting()`. That way the change can also be accounted for in journals and transactions.
Closes #671
=> Change currency from settings #671

app/Support/Metar.php, tests/MetarTest.php
Account for "KM" as unit for visibility, instead of just "SM". Closes #680
=> METAR: KM as unit in visibility #680

resources/js/maps/index.js
Hi nabeelio, I found a typo in `./resources/js/maps/index.js` which broke the `make build-assets` step in my testing
=> typo in dependency on 'leaflet.geodesic'

modules/Installer/Config/config.php, modules/Installer/Resources/views/install/index-start.blade.php, modules/Installer/Services/RequirementsService.php
Remove the call to `base_path()` and the use absolute paths reported by Laravel when checking the permissions of those paths (in case `/public` has been moved)
closes #693
=> Installer: Use absolute paths for permissions check #693

app/Exceptions/Handler.php, app/Http/Middleware/SetActiveTheme.php
Explicitly set the theme in the error handler, seems something changed in the behavior between Laravel 6 -> 7.  Refactor the middleware a bit so we can reuse that logic
closes #715
=> Use theme in error handlers #715

app/Repositories/ExpenseRepository.php, app/Services/Finance/PirepFinanceService.php, tests/FinanceTest.php
- Expenses for all airports were being applied. Fix for that, as well as making it possible later to extend the expenses to being applied on departure or arrival (only arrival airport now)
- Make sure expenses for other types are also restricted by the `ref_model_id`
Closes #729
=> All airports' expenses being applied to PIREP #729

app/Services/Metar/AviationWeather.php, tests/MetarTest.php, tests/data/aviationweather/kphx.xml
Fix METAR dropping the `fields=raw_text` parameter.
=> Fix METAR invalid parameter #738

app/Database/migrations/2020_03_27_174238_create_pages.php, app/Database/migrations/2020_06_09_141153_pages_add_link.php, app/Exceptions/UnknownPageType.php, app/Http/Composers/PageLinksComposer.php, app/Http/Controllers/Admin/PagesController.php, app/Http/Requests/UpdatePageRequest.php, app/Models/Enums/PageType.php, app/Models/Page.php, resources/views/admin/flash/message.blade.php, resources/views/admin/menu.blade.php, resources/views/admin/pages/fields.blade.php, resources/views/layouts/default/nav.blade.php
Note template changes
Closes #750
=> Add ability to use a link instead of a page #750

resources/views/layouts/default/profile/index.blade.php
This cosmetic change is a very small change to 2 items on the Pilot's Profile Page.
1.) Display the Users Rank Image "{{ $user->rank->image_url }}"
2.) also change the Order of the "Home Airport" text and value
=> Small Cosmetic Change to Rank & Home Airport Display

app/Support/Metar.php, modules/Awards/Awards/PilotFlightAwards.php, phpunit.xml, tests/MetarTest.php, tests/data/aviationweather/lfrs.xml
=> Metar: TEMPO and trend causing issue with values being overwritten

app/Http/Controllers/Api/UserController.php, app/Services/BidService.php, app/Services/FlightService.php, app/Services/UserService.php, tests/BidTest.php, tests/SimBriefTest.php, tests/TestData.php
=> Bids are missing subfleets in API response #867

modules/Awards/Awards/PilotHoursAwards.php
This award is based on the original PilotFlightAwards.php file but checks the Pilots Flight Time (In Minutes).
This award means you can create an award for a pilot that completes any amount of flight time (In Minutes).
=> Adding a new AwardClass for Flight Time

app/Contracts/Migration.php, app/Database/migrations/2020_09_30_081536_create_modules_table.php, app/Database/seeds/DatabaseSeeder.php, app/Models/Module.php, app/Services/Installer/DatabaseService.php, app/Services/Installer/MigrationService.php, app/Services/Installer/SeederService.php, app/Services/ModuleService.php, app/Support/Modules/DatabaseActivator.php
Something of a race condition happens when there are module migrations pending, but they're not picked up when the migration hasn't yet been loaded. This is an issue when there is seed data which depends on the migrations to run. So, before running the seeds, check for any pending migrations, but also in the installer, after running the initial migrations, check again for pending migrations, where the initial sets of modules that are running would have been loaded in.
cc @YashGovekar
=> Fixes for installer/modules race condition

app/Contracts/Award.php, app/Models/User.php, modules/Awards/Awards/FlightRouteAwards.php, tests/AwardsTest.php
=> FlightRouteAwards - fix if last pirep is empty/other error conditions

app/Console/Commands/CreateDatabase.php, app/Http/Controllers/Api/FlightController.php, app/Http/Controllers/Api/UserController.php, app/Http/Resources/Fare.php, app/Http/Resources/Flight.php, app/Providers/RouteServiceProvider.php, app/Services/BidService.php, app/Services/FareService.php, app/Services/FlightService.php, tests/FinanceTest.php, tests/FlightTest.php, tests/SubfleetTest.php, tests/TestData.php
- Adds new `fares` section in the flight response which should be used if there are overriding fares on the flight itself
Closes #899
=> Flight/Subfleet fares not returning in API #899

app/Http/Controllers/Api/FlightController.php, app/Http/Resources/Fare.php, app/Http/Resources/Flight.php, app/Models/Flight.php, app/Services/BidService.php, app/Services/FareService.php, tests/FinanceTest.php, tests/ImporterTest.php
Refactor the fares inheritance so it reads as `flight->(subfleet)->fare`, instead of just `flight->fare`.
Closes #905
=> Refactor fares inheritance #905

app/Services/FareService.php, app/Support/Math.php, tests/FinanceTest.php, tests/MathTest.php
Don't add a percentage to the base value, calculate it like someone would expect a percentage to be normally calculated.
Closes #925
=> Calculate percentage properly instead of adding to the base value #925

resources/views/layouts/default/flights/simbrief_briefing.blade.php
1. Added ATC Prefile options for IVAO and VATSIM
2. Added TAF reports for Origin, Destination and Alternate airports. 
* Technically TAF reports are required for flights more than 1 hour, so we need to see them on the briefing page too
3. Adjusted the height of OFP div to match the visual style with the WX section changes
=> Update Simbrief Briefing Display

app/Support/Metar.php, tests/MetarTest.php
**SKC** means **Sky Clear** or _Clear Skies_. , it is not used as an acronym for No Significant Changes Expected (which is NOSIG)
Rest is ok
=> Update Metar Decoding (Text Correction Only)

resources/views/layouts/default/flights/simbrief_briefing.blade.php
Fixed wrong EET and ENDURANCE values at IVAO & VATSIM prefile forms with a php function converting seconds to HHmm format. 
Also added **View Route At SkyVector** link (uses auto zoom to fpl route on High Enroute Charts) , thx Maco for his idea and original link.
=> Update SimBrief Briefing Blade

app/Http/Controllers/Frontend/SimBriefController.php, app/Providers/RouteServiceProvider.php, resources/views/layouts/default/flights/simbrief_briefing.blade.php
With this we will be able to generate a new briefing with SB after creating one.
- RouteServiceProvider : Added the route for remove function
- SimBriefController : Added the function to remove the simbrief ofp from db (or just null the flight_id if a pirep_id is provided for that simbrief ofp) , finally redirecting the user to flights.index
- simbrief_briefing.blade : Added the button next to Prefile Pirep button
=> SimBrief : Generate New Briefing

app/Http/Controllers/Frontend/SimBriefController.php, app/Providers/DirectiveServiceProvider.php, app/helpers.php, resources/views/layouts/default/flights/simbrief_briefing.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php
Replaces outdated old pr.
Same improvements apply to both SimBrief Controller and flights / simbrief_form.blade
- Uses the aircraft_id to get all necessary details to calculate random load according to load factor and variances. (Min and Max protections applied, load factor will never go above 100 and below 1)
- All possible values are sent to simbrief for more precise and customized flight plan generation
- Gets current utc time and adds 45mins to it for ETD and Date generation
- Different pax weights are used for Charter and Scheduled flights (also sent to SimBrief)
- Calculated random load figures are sent to SimBrief OFP as Dispatch Remark too
- Automatic SID/STAR type selection added to planning options (RNAV or Conventional)
- Step Climb logic applied (as per SimBrief documentation, …
=> SimBrief Planning System Update

app/Http/Controllers/Frontend/ProfileController.php, resources/views/layouts/default/profile/index.blade.php
PR fixes the Acars Config Download button not showing up at user profile bug #919 
Also fixes the problem where Generate New Api Key button not following user selections and generating a new key even if user clicks cancel.
=> Fix For Acars Config Download Button Not Working Bug #919

modules/Awards/Awards/PilotHoursAwards.php
!is_int was causing the check always return false even when user enters a proper value like 6000 or 30000 in admin/award settings.
We should use !is_numeric instead to see if it is a valid numeric value.
=> Fix PilotHoursAwards

app/Http/Controllers/Frontend/SimBriefController.php
PR fixes the problem for 0 load generation where va admins do not set load factor and variance values for their flights and also leave the general settings empty. In such cases, both loadmin and loadmax was returning 0 , resulting zero load.
Thanks @macofallico for figuring this out.
=> Failsafe for SimBrief random pax generation

app/Cron/Nightly/PilotLeave.php, app/Http/Controllers/Frontend/SimBriefController.php, app/Models/PirepFare.php, app/Services/FareService.php, app/Services/UserService.php, tests/TestData.php, tests/UserTest.php
Changed user leave so it uses the last PIREP ID or the created date/time of the user. Added tests.
Closes #1022
=> Fix pilot leave calculation #1022

resources/views/layouts/default/flights/simbrief_briefing.blade.php
Speed is now checked and leading zero is removed, also changed the initial altitude to full feet value like 23000 instead of just 230.
PR targets issue #1036 / (SimBrief) Wrong cruising ALT and wrong speed integer on prefile (VATSIM)
=> Fix for SimBrief VATSIM Prefile errors ( Issue #1036 )

app/Services/UserService.php
Query was checking status field instead of state field to find active users.
=> Fix findUsersOnleave Function

app/Database/migrations/2021_02_23_205630_add_sbtype_to_subfleets.php, app/Database/seeds/settings.yml, app/Http/Controllers/Frontend/SimBriefController.php, app/Models/Subfleet.php, resources/views/admin/subfleets/fields.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php
* Added SimBrief Type field to subfleets, can be used to assign simbrief airframes to subfleets and fix non existing or wrong types. If not used simbrief form will use aircraft's icao type code
* Added Passenger and Baggage weights to settings
* Added setting for using PhpVms Pilot/User  Ident as simbrief atc callsign
* SimBrief form code cleaned up a bit and improved. Now form supports both cargo and passenger fares to be used at the same time.
Generated passenger baggage weight will be reduced from aircraft's cargo capacity and remaining amount will be used for random cargo generation.
Also multiple cargo fares or any mix is possible now (like only cargo, only passenger, multiple cargo and passenger fares)
=> SimBrief Integration Update

app/Database/migrations/2021_02_23_150601_aircraft_add_fuelonboard.php, app/Database/seeds/settings.yml, app/Services/Finance/PirepFinanceService.php, app/Services/PirepService.php
PR aims to have realistic fuel debit calculations as in the real ops. When enabled, remaining fuel amounts from previous flight will be reduced from block fuel and airline will only pay for uplifted fuel amount.
If onboard fuel is enough for the flight or exceeds the required amount no fuel debit will be issued.
If this is the first flight of the aircraft or the tanks are dry, full block fuel will be treated as uplifted.
Disabled / uses current default (fuel_used will be debited)
Aircraft table also will hold the fuel_onboard value (not needed for calculations, just saving for displaying purposes)
=> Advanced Fuel Calculations

app/Services/Finance/PirepFinanceService.php
Due to an error at the settings check advanced fuel calculations was not working and defaulting to fuel used always.
=> Fix Advanced Fuel Calculations

app/Providers/AppServiceProvider.php, app/Support/ThemeViewFinder.php
Currently views from modules can be overridden in resources/views/layouts/<activetheme>/resources/views/modules/<modulename>
This override removes the duplicated "resources/views" part.
in igaster/laravel-theme a PR has been created but is not yet merged. This is considered a workaround until PR is merged into laravel-theme package
=> Optimize view paths for module views in theme folder

app/Database/factories/RoleFactory.php, app/Database/migrations/2021_03_18_161419_add_disableactivitychecks_to_roles.php, app/Models/Role.php, app/Services/UserService.php, resources/views/admin/roles/fields.blade.php, tests/TestData.php, tests/UserTest.php
=> Implemented variant B of #1078

app/Services/Finance/PirepFinanceService.php, app/Services/Importers/AirportImporter.php
PR aims to fix the problem where Airport GH cost is not defined but recored to db as 0.00 or 0 (default value for airports table)
In such cases settings/default apt gh cost will be used.
=> Fix For GH Costs

app/Http/Controllers/Frontend/DownloadController.php
Added multiple airline support to both Aircraft and Subfleet downloads, if the user has more than one active airline, downloads will display the airline name before the object name. Also sorted the returned results to have a better look at the blade.
=> DownloadController Improvements

app/Database/seeds/settings.yml, app/Http/Controllers/Frontend/SimBriefController.php, resources/views/layouts/default/flights/simbrief_aircraft.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php
Instead of passing subfleets to blade (and doing two foreach loops and ifs to populate the dropdown), we are building a proper aircraft list here.
Did not removed $subfleets from data being passed to blade on purpose, it may be removed later on.
=> Move SimBrief aircraft selection to Controller

app/Widgets/LatestPireps.php
Latest pireps should be ordered by `submitted_at` instead of `created_at` . 
Pirep may be created even a day before others (with the pause/resume ability we have in acars) but it gets submitted once when the flight is ended, thus I think it should be our reference to sort them in proper order.
=> Change LatestPireps Widget Sort Order

app/Exceptions/PrefileError.php, app/Http/Controllers/Api/PirepController.php, app/Listeners/PirepEventsHandler.php, app/Providers/EventServiceProvider.php, app/Services/PirepService.php
To abort a prefile, use:
```php
throw new \App\Exceptions\PrefileError('failing prefile because of something');
```
And that message should go up to ACARS
Closes #1110
=> Move the prefile event and add a new error exception

resources/views/admin/flights/subfleets.blade.php
Will show the subfleet airline logo or icao in the admin flight create page table.
=> Show Airline logo / icao to subfleets table

app/Database/migrations/2021_04_05_055245_flights_add_alphanumeric_callsign.php, app/Models/Flight.php, resources/lang/en/flights.php, resources/lang/es/flights.php, resources/lang/it/flights.php, resources/lang/pt-br/flights.php, resources/views/admin/flights/fields.blade.php, resources/views/layouts/default/flights/show.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php, resources/views/layouts/default/flights/table.blade.php
PR adds ability to define alphanumeric callsigns for flights, display them and use them during SimBrief OFP generation (if pilot ident as callsign option is not enabled)
Translations for en/es/it/pt-br added.
=> Alphanumeric Callsign For Flights

app/Cron/Hourly/RemoveExpiredLiveFlights.php
Using whereTime may present a problem for flights conducted during utc midnight and some active/live flights may be deleted with whereTime.
Scenario;
now     = today-01:00  utc
setting = 2 hours
date     = yesterday-23:00 utc
Any live pireps will/may be deleted with whereTime 'cause their last updated TIME will be maximum 00:59 which is smaller than 23:00.
=> Use where iso whereTime

config/session.php
Currently the session live time defaults to 2 hours, adding an env variable will allow us to change this on a per site basis
=> Allow session lifetime to be set in env variables

app/Database/seeds/settings.yml, app/Models/Subfleet.php, app/Services/Finance/PirepFinanceService.php
Add missing defaults for 100LL and MOGAS prices to admin settings and use proper subfleet fuel type at pirep finances. (instead of using always JET-A1)
Closes #1145
=> 100LL and MOGAS Fuel Cost

app/Cron/Hourly/RemoveExpiredLiveFlights.php
While deleting frozen/expired in progress pireps we should at least send a PirepCancelled event for those who are listening.
(or we may have a new PirepDeleted event to be issued in such cases, I think PirepCancelled is enough though)
=> PirepCancelled Event (Cron Expired Pirep Deletion)

app/Exceptions/AircraftNotAvailable.php, app/Services/PirepService.php
Check if the aircraft is available for flight (State : Parked / On Ground)
If not throw new exception **AircraftNotAvailable**
=> Check Aircraft Availability

app/Console/Commands/EmailTest.php, app/Console/Commands/ProcessQueue.php, app/Console/Cron/JobQueue.php, app/Console/Kernel.php, app/Contracts/Command.php, app/Listeners/MessageLoggedListener.php, app/Models/News.php, app/Notifications/Messages/AdminUserRegistered.php, app/Notifications/Messages/NewsAdded.php, app/Notifications/Messages/PirepAccepted.php, app/Notifications/Messages/PirepRejected.php, app/Notifications/Messages/PirepSubmitted.php, app/Notifications/Messages/UserPending.php, app/Notifications/Messages/UserRegistered.php, app/Notifications/Messages/UserRejected.php, app/Providers/EventServiceProvider.php, composer.json, composer.lock, config/logging.php, config/queue.php, resources/stubs/installer/env.stub
Use queues for notifications and process the queue in the cron instead of a separate worker. Closes #1154
=> Use queues for notifications #1154

resources/views/admin/flights/create.blade.php, resources/views/admin/flights/fields.blade.php
Remove scripts from create blade which are designed for edit blade in the first place (thus looking for flight object and its properties). 
No need to have an eyecandy date picker or a days selector, previous working version of create.blade was more than enough to manually add fights.
Closes #1199
=> Remove Scripts

app/Services/ImportExport/FlightImporter.php
* Handle Route and Level fields too during import.
* Also removed the check for `'visible' => true` from `firstorNew` 'cause va admin may be importing to update not visible flights too.
(by default all new flights are visible, so no affect on new flights)
Closes #1201
=> Fix Flight Importer

app/Http/Controllers/Admin/UserController.php, resources/views/admin/flights/fields.blade.php
* UserController: Use Role Repository and `selectBoxList` method instead of the model itself.
* Flight Fields: Add empty option to Days select field
Closes #939 
Closes #938
For both ; If users wants to clear out that fields, all options must be removed and empty/blank option must be selected before updating the record. Deleting only the days or roles without selecting the empty/blank option will not be enough to clear out that fields.
=> Fix Admin: UserController and Flight Edit

app/Http/Controllers/Frontend/FlightController.php
No need to list all IATA Flight Types at search dropdown, only used ones would be ok and simpler for users to follow.
Closes #1206 ( Feature Request )
Ps: DB:: was used on purpose instead of Flight Model or Repository to only get the codes.
=> Show only used Flight Types at Flight Search

Dockerfile
GD is used when uploading profile picture to convert the image. Doing this in the current docker container crashes the process and the stack-trace says that the GD module is missing.
=> Add GD PHP Extension for docker container

app/Contracts/Resource.php, app/Http/Middleware/ApiAuth.php, app/Http/Middleware/JsonResponse.php, app/Http/Resources/PirepFieldCollection.php, app/Support/Resources/CustomAnonymousResourceCollection.php, app/Support/Resources/CustomPaginatedResourceResponse.php, tests/ApiTest.php
Start as issues with Chinese language utf-8 problems in pagination (API was showing links/text). Remove those as they are not needed, just shrink down the API response in total. Also force the API to use `en` as the locale, just to prevent these weird issues from happening when they might be OK on the web side but errors in the encoding in JSON.
=> Remove extraneous data from API response; force API to en

app/Notifications/Messages/PirepPrefiled.php, app/Notifications/Messages/PirepStatusChanged.php, app/Notifications/Messages/PirepSubmitted.php
Use profile route for message author instead of using the pirep route twice in the same message.
Message Author will be linked to that user's own profile , flight will be linked to the pirep being used for the message.
=> Use Profile Route for Author URL (Discord Messages)

docker-compose.local.yml
docker up throwing error due to missing colon on the ./vendor folder
=> Fix  missing colon on ./vendor volume

app/Services/PirepService.php
`$fv['name']` should be used instead of `$fv->name` due to the nature of source data.
Fixes #1260
=> Fix PirepService

app/Http/Controllers/Admin/PirepController.php, app/Services/FareService.php
`$fares` was an **array** but was being handled like a _collection_ , which of course was causing problems while assigning a value to `$fare->pirep_id` and with the `$fare->save()` calls.
PR fixes both and Closes #1233 and #1244
=> Fix Admin / PirepController

app/Http/Controllers/Frontend/ProfileController.php, app/Repositories/UserRepository.php
Currently UserRepo returns either private or public fields, which is useful for profile display but comes with a logical problem for profile editing phase, which is already private to the user itself and there we need to have all custom profile fields. So the user can edit those when needed.
1. Remove the bool from the method call for edit ( Controller )
2. Alter the method to handle this new change ( Repository )
Closes #1287
=> Fix Private Profile fields not being editable

app/Services/ImportExport/SubfleetImporter.php
`hub_id` is not a mandatory field (both in model and database), so it should be `nullable` here too.
=> Fix SubfleetImporter

resources/views/admin/subfleets/fields.blade.php
As like the db and model, admins should be able to not choosing a hub for their fleets here.
=> Fix Admin/Subfleet Fields (for no Hub)

app/Services/PirepService.php
Moved `$default_state` logic below `PirepFiled` event, so admins can have some flexibility to define their own default states by listening that event.
Any ideas ?
Hopefully closes #1312
=> Default PirepState logic and location change

app/Services/PirepService.php
That `if` should return `true` when both conditions are met (pirep not accepted and not rejected yet), so **AND** must be used there ;) Sorry for the trouble.
Now it works and listens more carefully.
=> Fix logical operator

app/Models/Aircraft.php
When needed all (or some) simbrief packs may be reached from aircraft level
Like `whereNotNull('flight_id')` will return only active simbrief packs generated for that aircraft, this also can be used along with SimBrief Block Aircraft setting etc.
=> Add Aircraft > Simbrief relationship

app/Models/Flight.php, app/Models/Pirep.php, app/Models/User.php, app/Models/UserFieldValue.php
Just added `name` attribute to get the name of the related UserField model.
Now when needed,  below simple code works to reach desired field value directly.
`$user->fields->where('name', 'IVAO PID')`
`$user->fields->where('name', 'IVAO PID')->first()->value` 
Without the name attribute, it was possible only with field_id or by doing loops in the collection to find out the proper field value by name match.
=> Update UserFieldValue Model

app/Models/Aircraft.php
Recently added `BelongsToThrough` was not working due to missing trait / use.
=> Fix Aircraft Model | Add trait for relationship

app/Http/Controllers/Frontend/ProfileController.php, resources/views/layouts/default/dashboard/pirep_card.blade.php, resources/views/layouts/default/pireps/show.blade.php, resources/views/layouts/default/pireps/table.blade.php, resources/views/layouts/default/widgets/latest_pireps.blade.php
Found 3 places where `pirep->airline->code` and `pirep->ident` being used together resulting `TKTK1978/C.HR/L.19` style strange output.
Fixed those and also edited latest pireps widget blade to use pirep and aircraft idents.
Closes #1346
=> Fix `pirep->ident` usage issues

app/Http/Controllers/Frontend/AirportController.php, app/Http/Controllers/Frontend/DashboardController.php, app/Http/Controllers/Frontend/FlightController.php, app/Http/Controllers/Frontend/HomeController.php, app/Http/Controllers/Frontend/PirepController.php, app/Http/Controllers/Frontend/ProfileController.php, app/Http/Controllers/Frontend/SimBriefController.php, app/Http/Controllers/Frontend/UserController.php, app/Widgets/LatestNews.php, app/Widgets/LatestPilots.php
Practically eager loaded items needed for detailed display of flights and pireps, users etc.
=> Eager loading update for frontend controllers and widgets

app/Http/Controllers/Frontend/SimBriefController.php, app/Models/Aircraft.php
Fix the fares relationship which was causing trouble when a flight had assigned fares
=> Fix SimBrief Controller | flight relationships

app/Repositories/FlightRepository.php
Nothing special, like the distance field search should accept `greater than` and `less than` values for flight_time too.
=> Add flight_time to searchable fields

app/Database/seeds/settings.yml, resources/views/layouts/default/widgets/live_map.blade.php
=> Setting for how often the live map updates #1369

app/Http/Controllers/Auth/RegisterController.php
Get only active and displayed UserFields.
Current code `UserField::all()` generates an exception 'cause it tries to get *all* custom user fields even they are not displayed at register form or not active at all.
=> Fix new user register with custom fields (RegisterController.php)

app/Http/Controllers/Admin/FlightController.php, resources/views/admin/flights/index.blade.php
Add ability to export flights of an airline only.
When at admin > flights, select the airline and filter/show its flights by clicking the find button. Now the export button will generate the csv file only for that airline's flights. 
In a multi airline environment helps a lot and saves time during flight management via export/import.
=> Airline Flight Export

app/Database/migrations/2022_01_10_131604_update_awards_add_active.php, app/Listeners/AwardHandler.php, app/Models/Award.php, resources/views/admin/awards/edit.blade.php, resources/views/admin/awards/fields.blade.php, resources/views/admin/awards/table.blade.php
Add active/passive check for awards and update the handler to pass only `active` ones to the checking process when needed.
After migration all current awards defined by VA will be considered as active.
=> Add ability to change an award's active state

app/Contracts/ImportExport.php, app/Services/ImportExport/FlightImporter.php, app/Services/ImportExport/SubfleetImporter.php
Two fixes;
- Single value column entries with query string format are now properly handled like the multi value columns (ImportExport.php)
- Fixes the fare name update problem (FlightImporter.php and SubfleetImporter.php)
Closes #1378 
Closes #974
=> Fix flight and subfleet import with edited fares

app/Models/User.php
Current GDPR compliant Private Name attribute is not compatible with multi byte strings, when encountered it fails and returns an empty string for the name_private attribute.
`substr($last_name, 0, 1)` or just `$last_name[0]` is not multi byte compatible, therefore only solution is to use `mb_substr`.
It also supports encoding definitions like `mb_substr($last_name, 0, 1, 'UTF-8')`
Admin;
Before (Current model result)
After (Updated model result)
=> Update User Model (Name conversion for GDPR)

app/Database/seeds/settings.yml, app/Models/User.php
Adds a new setting to customize the ident or to use a fixed icao code in a multi airline environment.
If settings is null/empty, airline icao will be used as like before.
=> Custom Code for Pilot IDents

app/Database/migrations/2022_02_11_124926_update_users_add_notes.php, app/Models/User.php, resources/views/admin/users/fields.blade.php
PR will allow admins to add managerial notes to user/pilot records. Like a reject reason or some important notes to be stored and shared over admins.
Also if needed it can be used in reject/deny mail blades to send back some info to the applicant. 
* Migration to add `mediumtext` field to users table
* Model update to add the new field and hide it from arrays by default
* Admin blade update
=> Add Notes to Users

app/Database/seeds/settings.yml, app/Http/Controllers/Admin/AirlinesController.php, app/Http/Controllers/Admin/FlightController.php, app/Http/Controllers/Admin/SubfleetController.php, app/Http/Controllers/Admin/TypeRatingController.php, app/Notifications/Channels/Discord/DiscordMessage.php, app/Notifications/Messages/Broadcast/NewsAdded.php, app/Notifications/Messages/Broadcast/PirepFiled.php, app/Notifications/Messages/Broadcast/PirepStatusChanged.php, app/Notifications/Messages/Broadcast/UserRegistered.php, app/Notifications/NotificationEventsHandler.php, resources/views/admin/flights/fields.blade.php
**Controller :** Airlines, Subfleets, Type Ratings and exported Flights are sorted
**Blade :** Added WYSIWYG editor to flight remarks/notes field
**Notifications :**
- Mails > Added enabled/disabled settings for mails.
- Discord > Dashed out PirepPreFiled, re-enabled PirepStatusChanged with reduced messages
=> Admin and Discord Notification Improvements

app/Services/PirepService.php
- If a manual pirep gets saved before being submitted, state is set to **DRAFT**.
- That state is not being considered during `auto approval by rank` check when the pirep gets submitted.
- So it passes the check and gets **_IN PROGRESS_** state 'cause it is the default state defined.
Pull request adds **DRAFT** state to `auto approval by rank` check.
Closes #1420
=> Check DRAFT state too when deciding auto approval by rank

app/Http/Controllers/Frontend/DownloadController.php
`findOrFail` was needed there to catch the exception, otherwise it was failing on a fresh install :)
Closes #1429
=> Laravel9 | Frontend > Download Controller

app/Cron/Hourly/RemoveExpiredLiveFlights.php
Query should check both `state` and `status` to find suitable pireps for deletion.
Closes #1433
=> Fix Cron Deleting Paused Pireps

Makefile, README.md, docker-compose.dev.yml
Updated `docker-compose.local.yml` to `docker-compose.dev.yml` to reflect the correct docker files
=> Fix docker dev links

resources/views/layouts/default/flights/simbrief_form.blade.php
Follow up for improved SimBrief API, sending separate pax and bag weights is possible now.
Core v7 already had them separated ;)
=> Add baggage weight to acdata (SimBrief, Default Theme)

app/Http/Controllers/Admin/RolesController.php, resources/views/admin/roles/table.blade.php, resources/views/admin/roles/users.blade.php
Adds member count to roles\index and member list to roles\edit pages.
PS: It was there with a note "TODO" for ages, it is better to have a least a count and list there instead of nothing ;) Maybe we can update it later with ajax to add/remove users live.
=> Display Members of Roles (Admin Controller & Blade)

app/Services/FareService.php, app/Services/ImportExport/AirportImporter.php
- Fare Service : Return the note, do not force it to an empty string
- Airport Importer : Make IATA nullable (as in the model)
Closes #1465
=> Fare Service Fix and Airport Importer Update

app/Support/Money.php, tests/FinanceTest.php
Bug:
In [line 60](https://github.com/nabeelio/phpvms/blob/f30a3bc1efc24ca1ef91533d3e9c00bc2daebf5c/app/Support/Money.php#L60)  in Money.php, `$amount` is cast to an integer before multiplying by the currency subunit.
Fix:
Do multiplication first before casting to an integer
Test:
FinanceTest.php is updated to test floating point handling.
Closes #1483
=> Patch currency subunit conversion

app/Services/ImportExport/FlightImporter.php, app/Services/ModuleService.php
Fixed issue #1414  Issue occured while looking up for non exisiting airports.
Added code to check null values from `processAirport` function and changed return type of `processAirport` function from `Airport` to `Airport|null`
=> Bug fix #1414

app/Notifications/NotificationEventsHandler.php
As the title says, news should be broadcasted to only ACTIVE and ON LEAVE users, no need to use server resources to send out mails to inactive (pending, rejected, suspended, deleted) users.
Closes #1518
=> Send news to active and on leave users only

app/Database/migrations/2023_01_28_174436_add_lastlogin_at_to_users.php, app/Http/Controllers/Auth/LoginController.php, app/Models/User.php, resources/views/admin/users/fields.blade.php
Add a carbon timestamp for last login instead of using _updated_at_. Update login controller to save last login details along with user ip (both tied to the same setting due to GDPR)
Closes #1516 
**Possible Error/Exception Warning** 
If the admin is already logged off during update, when he/she tries to login after update there will be an exception about missing database field. 
**Workaround For Admins**
- Disable IP recording before update (re-enable it after completing migration and cleaning cache) or,
- Visit /update manually after the error (technically authentication is completed at that moment and process fails during model update only)
=> Last login TimeStamp

resources/views/layouts/default/flights/index.blade.php
This fixes the bug where when navigating between pages in the pagination, it clears out all the filters from the results view. This doesn't solve the issue for the form clearing.
=> Fix bug where clicking pagination clears filtered flights.

resources/views/admin/flights/fields.blade.php
A simple solution at blade level, which forces the form to use nautical miles (system unit) when editing a flight and passes that data back.
If this is a new flight creation, empty form field is displayed which will let v7 to calculate the distance during save operation or let the user to click calculate.
Closes #1543
=> Fix Flight Edit (fields.blade.php)

app/Http/Controllers/Auth/RegisterController.php
Function returns either a view or redirect, both should be allowed.
Fixes `production.ERROR: App\Http\Controllers\Auth\RegisterController::register(): Return value must be of type Illuminate\Http\RedirectResponse, Illuminate\View\View returned` problem reported by @dougjuk
=> Fix Return Type Problem

app/Http/Controllers/Admin/FlightController.php, resources/views/admin/users/fields.blade.php
Closes #1566 (Controller update)
Closes #1568 (Blade update)
- Removes the "blank" entry for flight type dropdown (admin > flights > add flight)
- Make Roles field and dropdown for role selector available only to admin / admin-user (admin > user > edit)
=> Admin | Flight Types and Users/Fields fixes

app/Http/Controllers/Frontend/FlightController.php, app/Http/Controllers/Frontend/PirepController.php, app/Http/Controllers/Frontend/UserController.php, app/Models/Aircraft.php, app/Models/Airline.php, app/Models/Airport.php, app/Models/Award.php, app/Models/Flight.php, app/Models/News.php, app/Models/Pirep.php, app/Models/Rank.php, app/Models/Subfleet.php, app/Models/Typerating.php, app/Models/User.php, composer.json, composer.lock, config/columnsortable.php, resources/views/layouts/default/flights/index.blade.php, resources/views/layouts/default/flights/table.blade.php, resources/views/layouts/default/pireps/index.blade.php, resources/views/layouts/default/pireps/table.blade.php, resources/views/layouts/default/users/index.blade.php, resources/views/layouts/default/users/table.blade.php
Allows sortable columns with pagination support.
Uses https://github.com/Kyslik/column-sortable 
Relevant models, controllers and default theme blades are updated to support sortable results with pagination.
=> Sortable Columns

config/app.php
This will allow to have all the default providers and aliases of laravel in addition to ours. Some were missing until today (like the aliase Str) which can cause errors with certain dependencies that use it . Also laravel 10 uses this format for its configuration by default.
=> Use default Providers and Aliases lists

app/Http/Resources/Flight.php, app/Models/Flight.php, app/Models/User.php, resources/views/layouts/default/flights/show.blade.php, resources/views/layouts/default/flights/table.blade.php
Closes #1607 
Adds callsign to flight ident, by checking simbrief callsign option.
When mentioned option is enabled, pilots will be forced to use their idents as callsign, so displaying a flight's callsign will be meaningless and confusing pilots. But when that option is not enabled, pilots should be able to see and use a flight's assigned callsign.
Callsign is either the flight number itself or a special alphanumeric string defined by airline per flight.
=> Update Flight Resource

resources/lang/de/auth.php
Closes #1610 
Remove the airline name used in the old translation, provide a nameless generic text for the case.
=> Remove airline name from German translation

app/Database/seeds/settings.yml, app/Http/Controllers/Frontend/SimBriefController.php
If enabled, this will allow a different load factor for cargo than for passengers by default. If a flight contains a custom load factor, then this custom load factor will take precedence over the default passenger/cargo load factor, and we will have a loading percentage in the same range for both passengers and cargo. If the flight does not contain a custom load factor, then we revert to the default settings, with (if enabled) a different range for the passenger load factor and the cargo load factor.
=> Add cargo load factor

app/Http/Controllers/Frontend/SimBriefController.php
If a pilot calls the ``/simbrief/generate`` url without any aircraft_id but he has booked the flight with an aircraft then it automatically takes this plane for OFP generation.
=> Automatically select the booked aircraft when none is chosen for simbrief OFP generation

app/Widgets/LatestPireps.php
Closes #1695 
Using `whereNotInOrder()` along with `recent()` somehow is not generating the expected result. Thus switched to more classic eloquent query, separated `whereNotIn()` and used `orderBy()` along with `take()`.
Also added the user model to eager loading.
PS: Admin > Pireps index controller should also use `submitted_at` field to sort the pireps for admins/staff, using `created_at` there creates confusion. This is handled in another PR thus not present here.
=> Improve LatestPireps Widget

app/Http/Controllers/Admin/PirepController.php, app/Http/Controllers/Admin/UserController.php, app/Models/Pirep.php, resources/views/admin/pireps/actions.blade.php, resources/views/admin/pireps/index.blade.php, resources/views/admin/pireps/pirep_card.blade.php, resources/views/admin/pireps/table.blade.php, resources/views/admin/users/edit.blade.php
- Controller changes to allow sortable results (pirep and user)
- Model change to add more sortable fields
- pireps/table change for new fields and sortable results
=> Sortable Admin Pireps List

app/Console/Kernel.php, composer.json, composer.lock, config/backup.php
This PR adds `spatie/laravel-backup` which will allow admins to backup their database. Here are some important setting that can be set in the .env:
-`BACKUP_ENABLED`: true/false (default)
-`BACKUP_DISKS`: comma-separated, local by default. Create disks in `config/filesystems.php`.
-`BACKUP_ARCHIVE_PASSWORD`: AES256 encryption password if set. empty/null = disabled (default)
-`BACKUP_FAILED_NOTIFICATIONS_CHANNELS`: `mail` (default), `discord`, `mail,discord`, or empty.
-`BACKUP_SUCCEED_NOTIFICATIONS_CHANNELS`: `mail`, `discord`, `mail,discord`, or empty (default)
-`BACKUP_NOTIFICATIONS_MAIL_TO`: Email for notifications.
-`BACKUP_DISCORD_WEBHOOK_URL`: Discord webhook URL.
-`BACKUP_DISCORD_USERNAME`/`BACKUP_DISCORD_AVATAR_URL`: Discord customization.
=> Add Laravel Backup

config/mail.php
On some VPS services with some control panels installed, outgoing mail verification may fail due to self signed certificates and peer verification.
To overcome this, these settings must be turned off and we should be able to change them in `.env` when needed.
=> Allow verification settings for smtp via env

app/Notifications/NotificationEventsHandler.php
No need to spam discord when the rank is not changed and the dispatched event is not related to ranks at all.
_Being tested on 3 live servers, do not merge directly_
=> Check Stat and Rank Change Before Dispatching Notifications

config/session.php, resources/stubs/installer/config.stub
This PR allows the use of Redis (or anything else) for sessions by adding the following lines to the .env file:
```
SESSION_DRIVER=redis
SESSION_CONNECTION=default
```
=> Move SESSION_CONNECTION to .env

app/Listeners/AwardHandler.php, app/Listeners/BidEventHandler.php, app/Listeners/DiversionHandler.php, app/Listeners/ExpenseListener.php, app/Listeners/FareListener.php, app/Listeners/FinanceEventHandler.php, app/Listeners/PirepEventsHandler.php, app/Listeners/UserStateListener.php
As discussed, this PR enables the use of queues for various listeners related to the dispatch of a PIREP. It's important to note that I couldn't find a way to enqueue all listeners for an event, so this won't work for modules. Therefore, I recommend module developers also use queues for their listeners.
Implementing queues allows us to perform certain tasks in the background asynchronously, resulting in significantly reduced processing times for end-users.
Additionally, there's no need to add the `shouldQueue` interface for notifications, as they are already queued. This is because the `App\Contracts\Notification` contract, which they all extend, already implements the `ShouldQueue` interface.
=> Use queue for listeners

app/Http/Controllers/Admin/MaintenanceController.php
Delete module and theme cache files when cleaning cache from admin area as they are not being deleted by laravel anymore.
Admin > Maintenance
* Application : Clears v7 application cache **AND module cache files**
* View : Clears v7 view (blade) cache **AND theme cache files**
Closes #1563
=> Delete Module and Theme cache files

app/Http/Controllers/Auth/OAuthController.php, app/Http/Controllers/Frontend/ProfileController.php, app/Providers/EventServiceProvider.php, app/Providers/RouteServiceProvider.php, composer.json, composer.lock, config/app.php, config/services.php, resources/views/layouts/default/profile/fields.blade.php, resources/views/layouts/default/profile/index.blade.php
Closes #1684 
We'll have to explain in the docs how to setup this.
You need to create an OAuth application in Discord's Developer Portal (like for RichPresence in VMSAcars, you can use the same app). https://discord.com/developers/applications
Then set these variables in `.env`
```
DISCORD_OAUTH_ENABLED=true
DISCORD_CLIENT_ID={your_client_id}
DISCORD_CLIENT_SECRET={your_client_secret}
```
I couldn't find `private_channel_id` in the Discord docs so I don't know what this field is in the users table and how to fill it. In addition the OAuth connection that I establish has an expiration time but since we don't want to connect the user but just retrieve their id I do not store the tokens to reconnect because we need to send a single request to discord. If we want to make requests to Discord …
=> Add Discord OAuth

app/Database/migrations/2023_12_17_181350_add_fields_to_aircraft.php, app/Models/Aircraft.php, app/Services/ImportExport/AircraftImporter.php, resources/views/admin/aircraft/fields.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php, tests/data/aircraft-update.csv, tests/data/aircraft.csv, tests/data/aircraft_empty_cols.csv
* DOW : Dry Operating Weight (or Operating Empty Weight)
* MLW : Maximum Landing Weight
* SELCAL : Selective Calling System Code
* SimBrief Type / as like in subfleet but for individual aircraft
All fields are optional, both admin (aircraft > fields) and frontend (flights > simbrief_form) blades updated for new fields.
**Important : Export / Import content is changed, old files may not be compatible for direct import anymore.**
Changes may come in handy for internal development and enhanced SimBrief integrations done by admins/airline devs.
=> Add new fields to Aircraft Model

app/Database/migrations/2023_12_15_154815_create_user_oauth_tokens_table.php
The migration sometimes fails on certain environments because of this constraint
=> hotfix: remove DB constraints in Discord OAuth

app/Notifications/Channels/Discord/DiscordMessage.php
Simply unset the empty image array from embeds instead of adding the logo to all notifications.
=> Proper fix for Discord Notifications

app/Services/UserService.php
When a user registers, and does not comply with e-mail validation, or somehow does not send any pireps, or admin decides to remove the record (test user, wrong registration etc) deleting from admin panel causes a `softdelete` by design.
This should be a `forceDelete` instead to remove the record permanently.
_If a user has pireps, implemented v7 "soft delete" logic works fine as it changes fields and keeps the record_
=> Fix new user removal

app/Database/factories/UserFactory.php, app/Database/migrations/2023_12_24_091030_drop_user_oauth_tokens_foreign_keys.php, app/Http/Controllers/Auth/OAuthController.php, app/Http/Controllers/Frontend/PirepController.php, app/Http/Resources/User.php, app/Models/User.php, app/Services/UserService.php, config/services.php, resources/views/layouts/default/auth/login_layout.blade.php, resources/views/layouts/default/auth/register.blade.php, tests/OAuthTest.php
Drop the foreign key if the migration managed to create it without error.
Do not create a new account via OAuth if the provider's email is already in the database. However, we do not link the account either for security reasons.
=> OAuth improvements

app/Services/FlightService.php, tests/FlightTest.php
A flight should NOT be marked as duplicate unless;
* Airline
* Flight Number
* Route Code
* Route Leg Number
* Origin
* Destination
* Scheduled Days
are identical with another flight.
We can import flights with same numbers but with different origins and destinations, but can not edit them in admin due to very limited "duplicate check".
Imagine you have a flight schedule as below;
TK1 AYT-DUS
TK1 DUS-BER
TK2 BER-AYT
You can import this as expected, but can not edit TK1 because v7 thinks it has a duplicate.
PR extends the check properly to consider origin, destination and weekdays.
=> Update FlightService > Duplicate Flight Check

config/themes.php
resolves #1776 
This is a workaround to the email issue linked above. It's also a good config option to have for those who need to set the default theme as different from default.
=> Add env config option to set default theme

app/Http/Controllers/Auth/LoginController.php
Having a different error message for a user account missing, and username/password being incorrect is a considerable security issue, because this could be a vector to fish for valid accounts.
=> Replace Auth Failed Message for User Account Missing

app/Database/migrations/2024_05_15_144813_add_internal_to_user_fields.php, app/Http/Controllers/Admin/UserFieldController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Frontend/ProfileController.php, app/Models/UserField.php, app/Repositories/UserRepository.php
This PR adds an "internal" column to the user fields. If a user field is marked as internal, then it cannot be edited by either admins or users. This allows modules to store information about users easily.
=> Add internal user fields

app/Services/LegacyImporter/PirepImporter.php
This PR updates the user's `last_pirep_id` when importing PIREPs from v5.
=> Map LastPirepID in Legacy PirepImporter

app/Http/Controllers/Api/MaintenanceController.php
As in `bin/cron.php` (see below), we need to create a fake console kernel and initialize it.
We are using a fake scheduler to run our cron jobs because some users don't have `proc_open` and can't use the real laravel scheduler. This fake scheduler calls console commands under the hood, which is why we need a console kernel. Normally, a console kernel isn't created for HTTP requests (only an HTTP kernel is created), so we need to initialize it manually.
https://github.com/nabeelio/phpvms/blob/677f3d5c89d02ea1b6d914430568cd27517bf9ec/bin/cron#L18-L30
=> Fix web cron

app/Events/NewsUpdated.php, app/Http/Controllers/Admin/DashboardController.php, app/Notifications/NotificationEventsHandler.php, app/Providers/RouteServiceProvider.php, app/Services/NewsService.php, resources/views/admin/dashboard/news.blade.php, tests/NewsTest.php
Closes #1813 
This PR adds the ability to edit news from the admin dashboard. However, it does not allow choosing whether to send notifications as mentioned in the issue. Notifications are managed by a listener that only receives the news model, so it wouldn't have access to a potential send email checkbox unless it was stored in the database (which wouldn't be very useful).
Updating news does not send any notifications because the NewsAdded event is not emitted.
This is entirely managed via AJAX
=> Add ability to edit news

app/Services/CronService.php
Since I only have VPS setups that have `proc_open`, I can't test and confirm that it displays the command with `/bin/cron` on an installation that doesn't have it.
@FatihKoz , I understand that you have servers without `proc_open`. Could you test this PR when you have a moment? Basically, in Admin > Maintenance, there is an example command to run for the cron. You should check if this example correctly shows the command `/bin/cron` on a server that doesn't have `proc_open`. On a server that does have it, it should show `artisan schedule:run`.
=> Recommend using Laravel scheduler when proc_open is available

app/Http/Controllers/Frontend/FlightController.php
Sorting with `sortable()` does not support multiple columns for default output, thus additional `orderBy()` usage is required for initial/default sorting to get expected results on page load (like admin controller)
=> Update FlightController (Default sort order fix)

app/Database/migrations/2024_07_02_164640_update_tokens_in_user_oauth_tokens.php
In the first implementation of OAuth, I forgot to account for the fact that tokens could be longer than 191 characters and thus not fit in a string... Since we're not using them at the moment, it's not a big problem, but if we ever want to use them, people who linked their accounts before this fix will need to unlink and then relink them.
=> Fix token columns type for OAuth

resources/views/system/installer/install/steps/step3-user.blade.php
Airport selection dropdown loop was faulty, it was passing in the country full name for the code field, thus failing on new installs.
=> Fix install error (country selection)

app/Http/Controllers/Api/FlightController.php, app/Http/Controllers/Api/PirepController.php, app/Http/Controllers/Api/UserController.php, app/Http/Resources/Rank.php, app/Http/Resources/SimBrief.php, app/Providers/RouteServiceProvider.php, app/Services/BidService.php, app/Services/UserService.php, tests/ApiTest.php, tests/UserTest.php
This PR adds various optimizations for the API, particularly in the case of large databases (as discussed with Nabeel).
Firstly, we remove certain unnecessary relationships, such as subfleets when searching for flights. To maintain backward compatibility, these relationships are still present on the default route; we've just added a query string that allows them to be removed or to include only specific ones (check which ones by endpoint). `?with=` allows all of them to be removed, for example, `?with=subfleets` allows loading only those related to subfleets.
Next, we've added eager loading in some places where it was missing.
Additionally, this PR fixes a bug in the endpoint that retrieves the finances of a PIREP (an error in the resource).
Finally, it disables the settings endpoint, …
=> API Optimizations

app/Http/Controllers/Admin/SubfleetController.php, resources/views/admin/subfleets/ranks.blade.php
Just as we can add multiple subfleets to a rank at once, we'll now be able to add multiple ranks to a subfleet at once.
=> Add ability to add multiple ranks to a subfleet at once

app/Http/Controllers/Api/FleetController.php, app/Http/Controllers/Api/FlightController.php
No need to add the main relationship if a sub relationship is being loaded by dot notation.
Also SimBrief relationships should be loaded with the aircraft
[Reference > Laravel 10x Docs](https://laravel.com/docs/10.x/eloquent-relationships#nested-eager-loading)
=> Nested Eager Loading

app/Http/Controllers/Frontend/FlightController.php, app/Repositories/Criteria/WhereCriteria.php, app/Repositories/FlightRepository.php, resources/views/layouts/default/flights/search.blade.php
Based on @BossOfGames 's idea and implementation for the usage of `whereIn()` as a new search criteria [_WhereCriteria_], I slightly changed his Type Rating based query to improve performance and added Aircraft ICAO Type Code based search capabilities. [_FlightRepository_]
According to VA settings, both **$type_ratings** and **$icao_codes** are built upon user capabilities (restricted settings) or all (relaxed settings). [_FlightController_]
Added both fields with conditional checks to default theme. [_search.blade_]
Enhances #1879 and provides other changes for this feature to be used with any theme.
Closes #1851
=> Search Flights By Type Rating and Aircraft ICAO Type Code

.github/workflows/build.yml
This should disable jobs related to artifacts and releases in the CI/CD pipeline when pushing to a fork (since these jobs aren't supposed to run on a fork).
This should work as expected, as we've used it before. However, after merging, please verify that all jobs are running correctly.
=> Run artifact/release jobs only on main repo

app/Http/Controllers/Frontend/CreditsController.php, app/Providers/RouteServiceProvider.php, resources/views/layouts/default/credits.blade.php
Provides a public credits page, which holds logo and links for phpvms v7 itself and lists any installed modules. It skips the default modules (Awards, VaCentral and Sample.)
Basically we need more lines in module.json file, so this should be documented on developers section otherwise only the name and status of the module (active/deactive) will be displayed.
```json
"version": null,
"readme_url": null,
"license_url": null,
"attribution": {
"text": null,
"url": null,
"img": null
},
```
If the design and logic is ok, can be merged.
Closes #1867
=> Credits Page (For phpvms v7 and installed modules)

app/Http/Middleware/SetActiveLanguage.php, config/languages.php
This PR introduces a system to detect the user's language preference based on their browser or system settings (through the `Accept-Language` HTTP header). If no language has been explicitly chosen by the user, this detected preference will be set as the default language.
=> Add user language preference detection as default fallback

app/Database/migrations/2024_11_22_182419_update_aircraft_table.php, app/Http/Resources/Aircraft.php, app/Http/Resources/Pirep.php
Provide support for extra ordinary weights.
_Even though it is not needed for weights except MTOW of A380, provide enough room for possible imaginary/experimental aircraft by updating all fields to support weights above 1 million pounds._
=> A380 Support and Fix For Aircraft Weights (API Resource)

app/Providers/RouteServiceProvider.php, public/assets/global/js/simbrief.apiv1.js
This code limits the number of requests to the route to 10 per minute. Once this limit is exceeded, requests are blocked, but the block only lasts for one or two minutes, so users are not locked out for several hours.
Additionally, the SimBrief code (frontend) has been updated to avoid sending more than 5 requests, with a delay of 1500ms between each request. This allows us to smooth out the requests we send afterward.
Example below:
You can see that I triggered the rate limiter, received 429 errors, then got the popup notifying me of a problem. If I regenerate about a minute later, I get a 200 status, and the generation works.
=> Add SimBrief Rate Limiting

resources/stubs/modules/provider.stub
closes #1901
This will fix the above. Modules will need to be updated, but at least new modules will be generated with the correct code.
One point of discussion. For the folder inside the theme, should we enforce the Pascal naming convention as seen by other modules (i.e. `DisposableBasic`, `DisposableSpecial`)? If so, I can switch all lower case to Pascal in another commit.
=> Update Module Stub to Fix Theme Overrides for Module Views

app/Http/Controllers/Admin/FlightController.php, app/Http/Controllers/Admin/Traits/Importable.php, app/Services/ImportService.php, resources/views/admin/flights/import.blade.php
This PR addresses an issue encountered when 3rd party modules write to the flights table, and these flights get deleted if the import checkbox is entered.
This PR:
- Adds a additional checkbox to only delete core flights
- Adds a confirmation dialogue for the delete all option
- Hides module generated flights from the admin flights table.
=> Modify Flight Importer Deletion Options

composer.json, composer.lock
By default, modules are registered after Filament in Laravel, which means panels registered in modules are not recognized. I can't remember exactly what I changed, but with this customized forked package, modules are now registered before Filament.
This ensures that Filament module panels can be discovered
=> [8.x] Fix module panels in Filament

app/Console/Commands/CreateDatabase.php, config/database.php
1. Add support for the mariadb driver in the `php artisan database:create` command.
2. Add support for db prefix in the mariadb driver
=> [8.x] Fix mariadb driver

resources/views/filament/plugins/module-links.blade.php
Check if the module name is in the path instead of the full url
=> [8.x] fix: active state detection in ModuleLinksPlugin

resources/views/layouts/seven/profile/fields.blade.php
These fields are managed through the OAuth controller when linking or unlinking your account. A user should not be able to edit them
=> [8.x] User shouldn't be able to edit ivao/vatsim id from profile

resources/views/layouts/beta/notifications/email-plain.blade.php, resources/views/layouts/seven/notifications/email-plain.blade.php
Applies to both `7.x` and `8.x`
=> [7.x] Add missing `,` in email-plain.blade.php

config/activitylog.php
Should be applied to both `v7` and `v8`
=> Update default activity log retention time

.htaccess
Okay, so basically, since we have a `vendor` folder at both the root and public levels, this rule in the `.htaccess` was preventing access to the `vendor` folder at the public level, which in turn blocked access to the LogViewer's assets.
This PR removes that rule, making it now possible for anyone using Apache to access the `public/vendor` folder. There's no risk of someone accessing the root `vendor` folder because there's a rule in the main `.htaccess` that redirects everything to `/public`.
A huge thanks to @FatihKoz for the help in testing this!
Closes #1992 
Should be merged in both `v7` and `v8`
=> Remove redundant `.htaccess` rule to allow apache access to `public/vendor`

app/Models/Casts/MoneyCast.php
In one of my installs I've noticed the balance column in the journals table was not getting set correctly by nightly cron task. It had minus values while sums should've been positive. (This effects @FatihKoz's Disposable Module's Manual Payment Feature)
**For example 6559487992 was turning into -2030446600**. Which immediately reminded me an integer overflow but I had to hunt for its source for a while. 
- This problem did not occur in every system. It was fine in Sail and in multiple VPS setups but not in shared hosting.
- It happened in 64 bit PHP and PHP_INT_MAX reporting _9223372036854775807_ 64 bit precision.
- Happened even when column was set as TEXT.
I was able to hunt it to this integer cast done to result of `Money()->getAmount()`. My guess is, in some systems this returns a …
=> [7.x] Fix integer overflow in journal balances 

app/Cron/Nightly/RefreshOAuthTokens.php, app/Database/migrations/2025_02_04_165053_update_icao_fields_size.php, app/Database/migrations/2025_02_09_085529_update_user_oauth_tokens.php, app/Http/Controllers/Auth/OAuthController.php, app/Models/UserOAuthToken.php, app/Providers/CronServiceProvider.php, app/Services/OAuthService.php, tests/OAuthTest.php
This pull request introduces several changes to enhance the OAuth token management system by adding a new service for refreshing tokens and updating related database schema and tests. The most important changes include creating a new `OAuthService` for token refresh, updating the database schema to rename a column, and modifying the `OAuthController` and `UserOAuthToken` model accordingly.
* [`app/Services/OAuthService.php`](diffhunk://#diff-a5294ccbe4598e5602859d8e1af59d7e485b31c9f95f8c18a605fe538564ef13R1-R42): Introduced a new `OAuthService` class with a method to refresh OAuth tokens before they expire.
* [`app/Database/migrations/2025_02_09_085529_update_user_oauth_tokens.php`](diffhunk://#diff-e48ae0f1fd4632b8bc64df95db67e10291cdec9f5b23da05191df05d4d09b109R1-R22): Added a migration …
=> Add Refresh Token System for OAuth Tokens

app/Filament/Resources/AirportResource/Pages/ListAirports.php
Simple PR adds back missing Import/Export CSV button to the Admin/Airports page.
This was tested with a CSV file from https://forum.phpvms.net/files/file/43-phpvms-7-airport-list/
Which uploaded into the mysql table.
=> [8.x] Add Import/Export CSV button back to Airports admin page

app/Filament/Resources/FlightResource.php
This PR addresses an issue that occurs when trying to sort flights by their ident, because ident is an attribute and not a column in the table
=> [8.x] Fix flight sorting

app/Filament/Resources/AircraftResource.php, app/Filament/Resources/FlightResource/RelationManagers/SubfleetsRelationManager.php, app/Filament/Resources/RankResource/RelationManagers/SubfleetsRelationManager.php, app/Filament/Resources/TypeRatingResource/RelationManagers/SubfleetsRelationManager.php
This PR adds the subfleet's airline name in the subfleet select text so that people can better understand which subfleet they are adding. For instance, if you have two subfleets named "A320" in two different airlines, you'll now know which one you're adding
=> [8.x] Add airline name in subfleet relationships

app/Filament/Resources/AwardResource.php, app/Filament/Resources/AwardResource/Pages/CreateAward.php, app/Filament/Resources/AwardResource/Pages/EditAward.php, app/Models/Award.php, public/uploads/.gitignore, public/uploads/awards/.gitignore
This PR enables the direct upload of images for awards, eliminating the previous requirement to only use urls. Now, you can either upload an image or enter a url. Additionally, the image upload feature includes an image editor for enhanced functionality.
The award model now includes an `image` attribute, allowing it to store either the URL of an uploaded file or a direct URL. This change is significant for theme developers transitioning from v7 to v8, as they will need to use `$award->image` in v8 to access uploaded images.
If desired, I can add an `image` attribute to v7 to maintain consistency across versions. This would enable the same theme or module to work seamlessly in both v7 and v8 using `$award->image`.
=> [8.x] Enable image upload functionality for awards

app/Filament/Resources/UserResource/Pages/EditUser.php
In v7, we had code to dispatch events when a user's state or rank was updated from the admin panel. This feature was forgotten during the migration to v8, and this PR restores it.
This pull request introduces event-driven updates to the `EditUser` page in the `UserResource` to handle state and rank changes. Key changes include the addition of event triggers, new private properties for tracking old values, and lifecycle hooks for saving operations.
* Added `UserStateChanged` and `UserStatsChanged` event imports to handle state and rank change notifications. (`app/Filament/Resources/UserResource/Pages/EditUser.php`)
* Introduced private properties `$oldState` and `$oldRankId` to store the user's previous state and rank ID for comparison during save operations. …
=> [8.x] Restore user update events in admin (state/rank)

app/Services/FlightService.php
closes #2054 
This addresses an issue where we need to disable the duplicate check for module-owned flights.
I have not fully tested this out to verify it's working. Hold off on merging until it's tested, or if there's a automated test that does test this code properly.
This will optionally need to be ported to v7.
=> Flight Duplicate Check for only Core Flights

resources/views/layouts/seven/flights/scripts.blade.php
We've noticed when using Disposable Special addon's Tour map wouldn't work. 
When I investigated the problem I tracked it to following.
- `ExpandTourMap()` javascript function in [DisposableSpecial/blob/main/Resources/views/tours/show.blade.php](https://github.com/FatihKoz/DisposableSpecial/blob/main/Resources/views/tours/show.blade.php) would not render on raw html response of laravel. Hence `@yield('scripts')` on app view was failing somewhere.
- Removing `@include('DSpecial::tours.legs_table')` would fix the issue.
- [DisposableSpecial/blob/main/Resources/views/tours/legs_table.blade.php](https://github.com/FatihKoz/DisposableSpecial/blob/main/Resources/views/tours/legs_table.blade.php) includes [resources/views/layouts/seven/flights/scripts.blade.php](resources/views/layouts/seven/flig …
=> fix: flights.scripts breaking view chain
