phpvms/phpvms

app/Http/Controllers/Frontend/DashboardController.php, resources/views/home.blade.php, routes/web.php
Fixed the frontend logout issue. Currently using form to post the logout.
=> Logout fix

app/Models/Airport.php, resources/views/admin/airports/fields.blade.php
Fix the adding of airport. It will now save the lat & Long and allow to put decimals in rather than just a rounded number
=> Fix adding of airport

app/Http/Controllers/Admin/AirlinesController.php, app/Models/Airline.php, resources/views/admin/airlines/fields.blade.php
Previously you were not able to edit an airline & it would return an error when adding one cause the redirect route wasnt set properly. this is fixed now
=> airline form fixes

composer.json
Incorrect file name for the .env file, updated the composer file.
=> Updated the composer file

.htaccess
It shows a blank page on install route in apache, it could be an rewrite error at line 
RewriteBase /
exactly, removing that line should be fix.
=> Install bug

resources/lang/es/auth.php, resources/lang/es/installer_messages.php, resources/lang/es/pagination.php, resources/lang/es/passwords.php, resources/lang/es/system.php, resources/lang/es/validation.php
=> ES translation

app/Support/Metar.php, tests/MetarTest.php
Fix unable to parse //////TCU part in METAR
=> Fix METAR issue

app/Http/Controllers/Admin/SettingsController.php, app/Repositories/SettingRepository.php, app/Services/UserService.php
=> Fix SettingsController saving boolean value as 'on'

app/Database/seeds/settings.yml, app/Http/Controllers/Admin/UserController.php, app/Http/Controllers/Auth/RegisterController.php, app/Models/User.php, resources/lang/en/auth.php, resources/lang/en/profile.php, resources/lang/it/auth.php, resources/lang/it/profile.php, resources/views/admin/users/fields.blade.php, resources/views/layouts/default/auth/register.blade.php, resources/views/layouts/default/profile/index.blade.php
Enhancement #129 
- Add option in admin settings whether to allow capturing of transfer hours
- Capture transfer hours in registration page
- Display transferred hours in profile page
- Allows admin to amend transferred hours in Edit User page
=> capture & display pilot transfer hours

resources/lang/es/profile.php
File affected: phpvms\resources\lang\es
=> More acceptable translation to opt-in (es)

docker-compose.yml, resources/lang/en/common.php, resources/lang/en/pireps.php, resources/lang/es/common.php, resources/lang/es/pireps.php, resources/lang/it/common.php, resources/lang/it/pireps.php, resources/views/layouts/default/pireps/fares.blade.php, resources/views/layouts/default/pireps/fields.blade.php
=> Fix pax count fields; add fuel used field #295

app/Services/ExportService.php, tests/ImporterTest.php, tests/data/airports_special_chars.csv
Refs #282. Export to utf-8 to preserve special characters
=> Change exporter to use utf-8 close #282

app/Services/Installer/SeederService.php, app/Support/Http.php, package.json, resources/views/admin/aircraft/expenses.blade.php, resources/views/admin/airports/expenses.blade.php, resources/views/admin/airports/fields.blade.php, resources/views/admin/airports/table.blade.php, resources/views/admin/expenses/fields.blade.php, resources/views/admin/fares/fields.blade.php, resources/views/admin/flights/fields.blade.php, resources/views/admin/pireps/fares.blade.php, resources/views/admin/ranks/fields.blade.php, resources/views/admin/settings/table.blade.php, resources/views/admin/subfleets/expenses.blade.php, resources/views/admin/subfleets/fields.blade.php, yarn.lock
=> Add step fields to enable decimal points on fields #342

app/Console/Command.php, app/Console/Commands/AcarsReplay.php, app/Console/Commands/ComposerCommand.php, app/Console/Commands/CreateDatabase.php, app/Console/Commands/DevCommands.php, app/Console/Commands/DevInstall.php, app/Console/Commands/ImportCsv.php, app/Console/Commands/NavdataImport.php, app/Console/Commands/TestApi.php, app/Console/Commands/Version.php, app/Console/Commands/YamlExport.php, app/Console/Commands/YamlImport.php, app/Console/Cron/Hourly.php, app/Console/Cron/Monthly.php, app/Console/Cron/Nightly.php, app/Console/Cron/Weekly.php, app/Cron/Nightly/RecalculateStats.php, app/Exceptions/SettingNotFound.php, app/Services/UserService.php
=> Additional logging for the stats recalculation

app/Listeners/NotificationEvents.php
=> Catch error messages in notifying

resources/views/layouts/default/flights/nav.blade.php, resources/views/layouts/default/flights/search.blade.php
I have made some minor CSS changes as discussed on Discord. 
Since I did not find the CSS file where to change it (all I tried did not work), I changed it in the files themselves. Feel free to adopt it as necessary.
=> Some minor CSS fixes as discussed on Discord

resources/views/layouts/default/airports/show.blade.php
=> fixes for issue #419

config/flare.php
Ref #455
https://github.com/laravel/framework/issues/30054
=> Avoid proc_open use #455

.travis.yml, .travis/deploy_script.sh, app/Console/Commands/Version.php, app/Contracts/Unit.php, app/Database/factories/AirportFactory.php, app/Database/seeds/dev/sample.yml, app/Providers/AppServiceProvider.php, app/Services/VersionService.php, app/Support/Metar.php, app/Support/Units/Distance.php, composer.json, composer.lock, config/version.yml, modules/Installer/Http/Controllers/ImporterController.php, modules/Installer/Http/Controllers/InstallerController.php, resources/stubs/installer/config.stub, tests/MetarTest.php, tests/VersionTest.php
Add PHP 7.4 support. Mainly fixes for null array handling, and updating some packages.
closes #463
=> Add PHP 7.4 support

.travis/deploy_script.sh, app/Console/Commands/Version.php, app/Providers/AppServiceProvider.php, app/Services/VersionService.php, app/helpers.php, modules/Installer/Http/Controllers/ImporterController.php, modules/Installer/Http/Controllers/InstallerController.php, tests/VersionTest.php
```Illuminate\Contracts\Container\BindingResolutionException
Target class [debugbar] does not exist.
```
=> Fix BindingResolutionError when debug toolbar isn't present

app/Services/ImportExport/FlightImporter.php, tests/ImporterTest.php, tests/data/flights.csv
Allow nullable field and calculate distance if nulled for flight import 
Refs#478
=> Allow nullable field and calculate distance if nulled

app/Http/Controllers/Admin/UserController.php
User update fix if no roles are selected/available
=> Error if there are no roles when editing a user #480

app/Http/Middleware/MeasureExecutionTime.php, app/Models/File.php, app/Models/User.php, app/Services/FareService.php, app/Services/PirepService.php, modules/Importer/Services/Importers/RankImport.php, modules/Importer/Utils/ImporterDB.php, modules/Updater/Providers/UpdateServiceProvider.php, tests/FinanceTest.php, tests/TestCase.php
=> Return the flight fares if there are no subfleet fares #488

.github/ISSUE_TEMPLATE/bug_report.md, app/Http/Kernel.php, app/Http/Middleware/SetActiveTheme.php, composer.json, composer.lock
Looks like some library injection is trying to load the general theme. Refs #491
=> 491 Installation Error

app/Models/Pirep.php, app/Services/GeoService.php
Geo service errors when looking up a PIREP and there are no ACARS updates
=> Fix GeoService errors when viewing PIREP #498

app/Http/Controllers/Api/FlightController.php, app/Http/Controllers/Frontend/FlightController.php, app/Repositories/Criteria/WhereCriteria.php, app/Repositories/FlightRepository.php, app/Repositories/SubfleetRepository.php, resources/lang/en/common.php, resources/lang/es/common.php, resources/lang/it/common.php, resources/views/layouts/default/flights/search.blade.php, swagger.yml, tests/FlightTest.php
API parameter to search for flights.
=> Search flights by subfleet #484

app/Database/seeds/dev/users.yml, app/Database/seeds/permissions.yml, app/Exceptions/Handler.php, composer.lock, modules/Updater/Providers/UpdateServiceProvider.php, resources/docker/php/Dockerfile, resources/views/layouts/default/dashboard/index.blade.php, resources/views/layouts/default/nav.blade.php
Admin link in dropdown was only showing if you had the `admin` role, not also the `admin-access` ability applied to a new role. closes #509
=> Show admin dropdown for admin-access ability

resources/views/admin/flights/subfleets.blade.php
=> Correct text for no subfleets #507

app/helpers.php, resources/views/system/errors/not_installed.blade.php
Add a `public_url()` helper, direct to the installer using that.
closes #513
=> Add a public_url() helper #513

app/Http/Routes/web.php
=> Set PIREPs page to public

app/Http/Routes/web.php
=> Fix PIREP edit endpoint

app/Cron/Hourly/RemoveExpiredLiveFlights.php
=> Fix import during flight cron #532

app/Http/Routes/web.php
=> PIREPS resource except for show

.travis.yml, .travis/deploy_script.sh, app/Http/Controllers/Admin/MaintenanceController.php, app/Http/Routes/admin.php, config/self-update.php, resources/views/admin/maintenance/index.blade.php, resources/views/admin/maintenance/update.blade.php
- Add a zip file which gets uploaded
- Use existing update chec
- Use only the `update()` call from https://github.com/codedge/laravel-selfupdater to run the update
=> Auto-update functionality #449

app/Http/Controllers/Admin/AircraftController.php, app/Http/Controllers/Admin/AirportController.php, app/Http/Controllers/Admin/ExpenseController.php, app/Http/Controllers/Admin/FareController.php, app/Http/Controllers/Admin/FlightController.php, app/Http/Controllers/Admin/SubfleetController.php, app/Http/Controllers/Admin/Traits/Importable.php, app/Models/Enums/ImportExportType.php, resources/views/admin/common/import.blade.php
- Add checkbox to delete previous data, pass it to call which already exists
- move all the import logic into a generic Trait and add an enum for the import/export type
- closes #490
=> Add checkbox to clear previous data when importing #490

app/Events/PirepCancelled.php, app/Events/PirepPrefiled.php, app/Events/PirepUpdated.php, app/Http/Controllers/Api/PirepController.php, app/Services/PirepService.php
Additional PIREP events. closes #436
=> Add additional events for PIREP states #436

app/Database/migrations/2020_02_12_141152_expenses_add_flight_type.php, app/Http/Controllers/Admin/ExpenseController.php, app/Models/Expense.php, app/Models/Pirep.php, app/Models/Traits/ReferenceTrait.php, app/Services/Finance/PirepFinanceService.php, resources/views/admin/expenses/fields.blade.php, tests/FinanceTest.php
- Set an expense type of specific flight types
- Add new column `flight_type` which has comma-delim list of applicable flights
- Closes #348
=> Set expenses on specific flight types #348

app/Database/seeds/settings.yml, resources/views/admin/menu.blade.php, resources/views/admin/settings/table.blade.php, resources/views/layouts/default/app.blade.php
=> Add Google Analytics tracking ID to settings and to main template #382

app/Contracts/Controller.php, app/Database/migrations/2019_06_19_220910_add_readonly_to_roles.php, app/Database/migrations/2019_07_16_141152_users_add_pilot_id.php, app/Database/migrations/2019_09_16_141152_pireps_change_state_type.php, modules/Installer/Http/Controllers/InstallerController.php, modules/Installer/Resources/views/flash/message.blade.php, modules/Installer/Resources/views/install/steps/step1-requirements.blade.php, modules/Installer/Services/ConfigService.php
Several migrations were not taking the table prefix into account, so install was failing.
=> Fix migrations when table prefix is involved #442

app/Services/CronService.php
Adjust the suggested argument with `-d register_argc_argv=On`.
closes #553
=> Add the argc_argv flag for the cgi exec #553

app/Http/Controllers/Frontend/FlightController.php, resources/views/layouts/default/flights/search.blade.php
=> Missing $subfleet error on bids page #561

app/Http/Controllers/Frontend/ProfileController.php, resources/views/layouts/default/profile/index.blade.php
Seems to happen when viewing someone's profile but not 100% sure, can't duplicate. Closes #560
=> Add extra check for  being set #560

modules/Installer/Config/config.php
=> Add bcmath to the required extensions list #558

modules/Updater/Resources/views/downloader/downloader.blade.php, modules/Updater/Resources/views/index-start.blade.php, modules/Updater/Resources/views/steps/step1-no-update.blade.php, modules/Updater/Resources/views/steps/step1-update-available.blade.php, modules/Updater/Resources/views/steps/step2-migrations-done.blade.php, modules/Updater/Resources/views/steps/step3-update-complete.blade.php
=> Fix the namespace path on updater templates #570

app/Http/Controllers/Api/AcarsController.php, app/Http/Controllers/Api/PirepController.php, app/Models/Traits/HashIdTrait.php, app/Support/Utils.php, config/themes.php, tests/AcarsTest.php
=> Upsert on ACARS positions #572

resources/views/admin/users/fields.blade.php
=> Fix edit pilot error (Facade\Utils missing) #576

Makefile, app/Database/factories/UserFactory.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Requests/CreateUserRequest.php, app/Services/UserService.php, composer.json, composer.lock, modules/Installer/Http/Controllers/InstallerController.php, resources/views/layouts/default/pireps/show.blade.php, tests/RegistrationTest.php, tests/UserTest.php
=> Respect home hubs setting for registration #580

modules/Importer/Services/Importers/RankImport.php
Only a single-rate from legacy, so just set that rate to both the ACARs and manual pay
refs #443
=> (Importer) Set the pay rate for the ranks #443

app/Cron/Nightly/RecalculateStats.php, app/Services/AircraftService.php, modules/Importer/Resources/views/step1-configure.blade.php, modules/Importer/Services/Importers/FinalizeImporter.php, tests/PIREPTest.php
=> Recalcuate aircraft stats in nightly cron and importer #585 #443

app/Http/Controllers/Admin/AircraftController.php, app/Models/Aircraft.php, composer.lock
- Validation to require aircraft status
- Don't show blank option when listing statuses
Closes #603
=> Aircraft status field blank causes error #603

app/Http/Resources/Fare.php, app/Http/Resources/Subfleet.php
Include the fare information in the response for subfleets.
Closes #608
=> Fare information not included in subfleet response #608

app/Database/migrations/2020_03_04_044305_flight_field_nullable.php, modules/Updater/Resources/views/app.blade.php, resources/views/admin/flights/index.blade.php
Causes confusion
- Allow the `flight_field_values` column to be nullable for blank value
=> Remove the flight fields link from admin #614

modules/Installer/Config/config.php
Makes it v difficult to debug and clearing caches doesn't seem to work properly.
Closes #625
=> Disable using apc/opcache by default if found #625

modules/Importer/Services/Importers/AircraftImporter.php
- Account for aircraft ICAO in subfleet
- If the `airline` column exists, use that for the subfleet 
- Account for last location, if that column exists
closes #628
=> Account ICAO for subfleet, airline/location if columns exist #628

app/Models/Observers/AircraftObserver.php, modules/Importer/Services/Importers/AircraftImporter.php
Incorrect field name. Also add `strtoupper()` in the observer for the `Aircraft` model
=> Fix airline mapping for aircraft #628

app/Database/migrations/2020_03_28_174238_page_icon_nullable.php, app/Http/Kernel.php, app/Providers/RouteServiceProvider.php
Make sure the theme is wrapped around all of the frontend routes. Closes #638
=> Auth routes not using themes #638

app/Http/Composers/PageLinksComposer.php, app/Support/Utils.php, composer.json, composer.lock, tests/UtilsTest.php
=> Domain detection failing for .co.uk, etc #647

composer.lock, package.json, yarn.lock
Address vulnerability messages from Github
=> Upgrade packages with security alerts

app/Providers/RouteServiceProvider.php, resources/views/layouts/default/users/table.blade.php
- Add `/users/{id}` and `/pilots/{id}` link/page
Closes #655
=> Fix pilots page now showing up #655

app/Services/BidService.php, tests/BidTest.php, tests/SimBriefTest.php
Bids aren't showing simbrief/flight data properly
Closes #664
=> Load Simbrief and flight data when getting bids #664

app/Http/Controllers/Frontend/PirepController.php
=> Check for SB being avail before filing #668

app/Contracts/Repository.php, app/Database/seeds/settings.yml, app/Http/Controllers/Admin/AirlinesController.php, app/Repositories/AirlineRepository.php, app/Services/AirlineService.php, modules/Installer/Http/Controllers/InstallerController.php
=> Journal not created when airline is created #667

composer.lock, modules/Installer/Http/Controllers/InstallerController.php, modules/Installer/Resources/views/install/steps/step2-db.blade.php
DI/import was incorrect. DB check also pointing to wrong endpoint.
Closes #677
=> Fix airline creation in installer #677

app/Contracts/FormRequest.php, app/Database/migrations/2020_03_28_174238_airline_remove_nullable.php, app/Http/Requests/UpdateAirlineRequest.php, tests/AirlineTest.php
* Check for IATA/ICAO already being used
* Allow blank value (remove UNIQUE index because null != blank)
Closes #679
=> Blank/null IATA code isn't unique when added #679

app/Database/seeds/dev/sample.yml, app/Models/Aircraft.php, resources/views/admin/aircraft/table.blade.php, tests/PIREPTest.php
* Aircraft row not using hours fields
* Add tests for aircraft hours
closes #683
=> Aircraft hours not showing/incrementing #683

app/Database/seeds/permissions.yml
Aircraft is missing in Permissions Seed
=> Update Permissions Seed

app/Http/Controllers/Admin/MaintenanceController.php, app/Services/VersionService.php, modules/Updater/Http/Controllers/UpdateController.php, resources/views/admin/maintenance/update.blade.php
- Don't show an update available if a latest version hasn't been found
Closes #707 closes #700
=> Auto-Update fixes #707

app/Http/Controllers/Admin/MaintenanceController.php
Make sure the updater module is enabled before attempting to forward to/complete an update
#707
=> Make sure the Updater module is enabled #707

app/Http/Controllers/Auth/LoginController.php, app/Services/PirepService.php, resources/views/layouts/default/dashboard/index.blade.php, tests/PIREPTest.php
- Allow user who is on leave to log in
- Show a message on the dashboard that the user is on leave
- Add test to make sure that the pilot's status is changed back to active
close #719
=> Allow on-leave user to login

Makefile, app/Console/Commands/CreateDatabase.php, app/Contracts/Command.php
- Read the command to run from a string
Closes #724
=> Fix params for launching process #724

resources/views/layouts/default/flash/message.blade.php, resources/views/layouts/default/flash/modal.blade.php
Update the flash templates to the latest ones from laracasts/flash. Closes #739.
=> Update the flash messages #739

app/Models/Subfleet.php
Add fields not saving to the `$fillable` propety of the model. Closes #731
=> Fleet properties not saving #731

app/Http/Composers/PageLinksComposer.php, resources/views/layouts/default/nav.blade.php
Fix for public pages not showing when not logged in. Note template changes. Closes #708
=> Fix public pages not showing #708

resources/views/admin/pireps/index.blade.php
=> Fix the search route for pending PIREPs #752

app/Events/AcarsUpdate.php, app/Http/Controllers/Api/AcarsController.php, modules/Vacentral/Listeners/AcarsUpdateListener.php, modules/Vacentral/Listeners/PirepAcceptedEventListener.php, modules/Vacentral/Providers/EventServiceProvider.php
=> Add ACARS update event #755

app/Services/Finance/PirepFinanceService.php
=> Add spacing to fare labels #763

app/Exceptions/Unauthorized.php, app/Http/Controllers/Frontend/PageController.php, app/Providers/RouteServiceProvider.php, docker-compose.yml
=> Check public pages for authorization #761

app/Services/UserService.php, tests/UserTest.php
=> Check for null values when checking pilot ID #760

app/Http/Controllers/Frontend/ProfileController.php, app/Repositories/UserRepository.php
=> Fix missing user fields #785

app/Providers/RouteServiceProvider.php, modules/Installer/Providers/InstallerServiceProvider.php, modules/Installer/Resources/views/install/index-start.blade.php, modules/Updater/Providers/UpdateServiceProvider.php, modules/Updater/Resources/views/index-start.blade.php
=> Fix clear cache errors with duplicate route names #759

app/Exceptions/AircraftInvalid.php, app/Http/Controllers/Frontend/PirepController.php, app/Services/PirepService.php, tests/AcarsTest.php
=> Fix for aircraft not being detected at departure airport #781

public/index.php
=> Detect the phpvms folder one root level above #798

app/Database/factories/AircraftFactory.php, app/Database/migrations/2020_09_03_141152_aircraft_add_mtow.php, app/Models/Aircraft.php, resources/views/admin/aircraft/fields.blade.php, tests/ApiTest.php
Add MTOW to db and expose MTOW and ZFW for entry in the admin panel 
Closes #775
=> Add MTOW and ZFW to aircraft editor #775

app/Http/Controllers/Api/UserController.php, app/Http/Resources/User.php, app/Services/UserService.php, tests/TestData.php, tests/UserTest.php
=> Make sure proper subfleets are returned as part of the user profile #848

resources/lang/en/profile.php, resources/lang/es/profile.php, resources/lang/it/profile.php, resources/lang/pt-br/profile.php, resources/views/layouts/default/profile/index.blade.php
Hi
This PR solve the issue https://github.com/nabeelio/phpvms/issues/841 with this new feature
Regards!
=> Add API Key visual protection

resources/views/layouts/default/profile/index.blade.php
some of the 'H2' and 'P' tage had missing classes 
<h2 class="card-title">
<p class="card-text">
=> Cosmetic change to standardise boxes on profile

app/Contracts/Migration.php, app/Database/migrations/2018_01_28_180522_create_awards_table.php, app/Database/seeds/dev/sample.yml, app/Database/seeds/dev/users.yml, app/Http/Controllers/Admin/UserController.php, app/Http/Controllers/Frontend/ProfileController.php, app/Models/User.php, app/Providers/RouteServiceProvider.php, resources/lang/en/profile.php, resources/lang/es/profile.php, resources/lang/it/profile.php, resources/lang/pt-br/profile.php, resources/views/admin/users/awards.blade.php, resources/views/admin/users/edit.blade.php, resources/views/layouts/default/home.blade.php, resources/views/layouts/default/profile/index.blade.php
=> Show awards on user profile #703

resources/views/admin/awards/table.blade.php
This is a small Cosmetic Fix to correctly display the Award Image in the Admin Awards UI Table
=> Cosmetic Fix to display Award Images in Admin View

app/Repositories/ExpenseRepository.php, app/Services/ImportExport/ExpenseExporter.php
=> Fixed Export Expenses #701

app/Database/seeds/settings.yml, app/Http/Controllers/System/UpdateController.php, app/Services/ImportExport/AirportImporter.php, app/Services/Importers/AirportImporter.php, tests/ImporterTest.php, tests/data/airports.csv
Fix for Issue #829 and minor change of Updater redirecting to Login instead of Admin.
=> Default values for automatically added airports #829

.travis.yml, app/Database/migrations/2020_11_20_044305_modify_pages_size.php
=> Change the body size to medium text #920

app/Models/Subfleet.php, app/Services/ImportExport/SubfleetImporter.php, tests/data/subfleets.csv
=> Add missing columns from subfleet export #926

resources/views/layouts/default/widgets/latest_pireps.blade.php
Added flight number, used aircraft registration (and icao type) instead of name
=> Update Latest Pireps Widget

resources/views/layouts/default/flights/search.blade.php
Added the ability to select and search an airline's flights. Will be usefull in multiple airline installations/configs.
=> Update Flight Search Form

resources/views/admin/pireps/index.blade.php, resources/views/admin/pireps/pirep_card.blade.php
Removed unnecessary div tags to fix the broken display problem, defined the div class with a php code.
=> Fix For Issue #952 / Formatting on admin pirep page

app/helpers.php
Add helpers instead of having to load the `KvpRepository` class
=> Add helpers kvp() and kvp_save()

app/Http/Resources/User.php
We should be able to send the private name with the api too.
=> Update User.php (for api output)

app/Console/Commands/DevInstall.php
Pointing to wrong location of file which is throwing errors as a result
=> Fix location of configservice within devinstall

resources/views/layouts/default/widgets/weather.blade.php
- Fixed the problem where values are not displayed when the reported wind,temp and dewpoint are 0 (zero).
- Fixed the hPa number formatting, there is no need to add 2 more digits to it, it is a plain 4 digit value always (like 1013 or 1024, it is never reported nor used as 1013,58 or 1024,35 etc).
- Corrected the display order, as it should be read (or say decoded).
- Also added decoded Current and Recent Weather Situations, RVR and Runway Condition reports.
_RVR report needs improvement in the Support / Metar.php too, it only reports nmi as the distance as far as i saw but it should be able to report meters too._
=> Update Weather Widget Blade

app/Widgets/LiveMap.php, resources/views/layouts/default/widgets/live_map.blade.php
Added the ability to enable/disable flight table display below the map.
- Controller: Default/protected configuration for table is 'on'
- Blade: Checks the passed in config(table) variable to enable/disable the flights table below the map.
Also changed the aircraft.name to aircraft.registration in the flight table
=> LiveMap Widget Update

resources/views/layouts/default/flights/simbrief_briefing.blade.php
Fixed Estimate Enroute Time (EET) display (it was using Scheduled Enroute Time)
=> SimBrief Briefing Display Fix

resources/views/layouts/default/flights/simbrief_form.blade.php
PR fixes the issue where load factor and variance being reported 0 to simbrief form, where user does not provide any values for each and wants to use general settings per flight.
Quick fix for issue #1001
=> Fix For Load Factor and Variance Bug

app/Http/Controllers/Frontend/SimBriefController.php, resources/views/layouts/default/flights/simbrief_form.blade.php
Move the logic into the controller. Closes #1001
@FatihKoz @arobsco
=> Move loadmin/max into the controller

app/Http/Controllers/Admin/AwardController.php
=> Fix AwardController - Text Correction

app/Http/Controllers/Frontend/ProfileController.php, resources/views/layouts/default/profile/index.blade.php
PR fixes two issues ;
1. Profile Fields not showing up on user.profile
2. Profile Fields not showing up on user.profile.edit
Profile.index was looking for "public" to be true, while controller was sending "private" and it was not boolean.
Also profile controller was not sending the fields to the edit.blade. Both fixed and working now
=> Fix Profile Fields

public/assets/frontend/css/styles.css
This edit hides the dropdown menu while being closed on mobile view
=> Update style.css for better mobile experience

app/Database/migrations/2021_02_10_044305_change_acars_vs_type.php, config/mail.php
=> ACARS table `vs` int to double

app/Database/migrations/2021_02_10_044305_update_sessions_table.php, app/Database/migrations/2021_02_11_044305_update_sessions_table.php, resources/stubs/installer/config.stub
https://laravel.com/docs/8.x/session#database
=> Update the sessions table

app/Console/Kernel.php, app/Cron/Hourly/DeletePireps.php, app/Cron/Monthly/ApplyExpenses.php, app/Cron/Nightly/ApplyExpenses.php, app/Cron/Nightly/ClearExpiredSimbrief.php, app/Cron/Nightly/NewVersionCheck.php, app/Cron/Nightly/PilotLeave.php, app/Cron/Nightly/RecalculateBalances.php, app/Cron/Nightly/RecalculateStats.php, app/Cron/Nightly/SetActiveFlights.php, app/Database/seeds/settings.yml, app/Http/Controllers/Admin/PirepController.php, app/Http/Controllers/Frontend/PirepController.php, app/Providers/CronServiceProvider.php, app/Services/PirepService.php, resources/views/admin/pireps/actions.blade.php
=> Implement PIREP deletion #1014

app/Http/Resources/Pirep.php, app/Models/Pirep.php, tests/PIREPTest.php
also add further checks in PIREPTest->testUnitFields
Bug was mentioned by @FatihKoz in #1040
=> Add unit conversion handling for block_fuel like for fuel_used

app/Services/Finance/PirepFinanceService.php
=> Fix Finance Memo (Ground Handling)

app/Http/Controllers/Frontend/SimBriefController.php
=> Urgent Fix For SimBriefController

app/Database/migrations/2021_03_25_213017_remove_setting_removebidonaccept.php, app/Database/seeds/settings.yml, app/Listeners/BidEventHandler.php, app/Services/BidService.php, tests/PIREPTest.php
As discussed on discord, bids should always be removed after filing a PIREP
=> remove remove_bid_after_accept setting

app/Http/Controllers/Frontend/PirepController.php, app/Http/Requests/UpdatePirepRequest.php, public/assets/frontend/css/styles.css, resources/views/layouts/default/pireps/show.blade.php, resources/views/layouts/default/widgets/live_map.blade.php
=> fix map-info-box display

app/Support/ThemeViewFinder.php
Solution in #1081 did not work for windows machines...
=> Followup to #1081

app/Models/Airport.php, app/Services/AirportService.php, tests/AirportTest.php, tests/TestCase.php
Morph `tz` value into `timezone`
=> Save airport timezone

app/Services/AirportLookup/VaCentralLookup.php
=> fetch timezone on airport lookup

app/Http/Requests/UpdatePirepRequest.php
Fixes issue being unable to save pirep edits from the admin section due to incorrect variable being used
=> Fix issue with being unable to save pirep edits

resources/views/admin/pireps/actions.blade.php
will show the pirep in new tab/page placeholder for having a pirep map in admin
=> Add "View Pirep" In pirep cards

app/Http/Controllers/Admin/FlightController.php
Useful if having multiple VAs subfleet types 
Nabeel this edit i made  might be rubbish, works but......
=> Adds Airline Icao to Subfleet Select in Flight Create

app/Cron/Hourly/DeletePireps.php, app/Cron/Hourly/RemoveExpiredBids.php, app/Cron/Hourly/RemoveExpiredLiveFlights.php
We should be using whereTime instead of whereDate
https://laravel.com/docs/8.x/queries#additional-where-clauses
`The whereDate method may be used to compare a column's value against a date`
=> Fix for Hourly Crons

.github/scripts/env.php, .gitignore, .htaccess, Dockerfile, app/Console/Commands/CreateConfigs.php, app/Console/Commands/DevInstall.php, app/Console/Commands/RewriteConfigs.php, app/Database/migrations/2021_04_10_055245_migrate_configs.php, app/Http/Controllers/System/InstallerController.php, app/Services/Installer/ConfigService.php, config/app.php, config/logging.php, config/services.php, resources/docker/php/Dockerfile, resources/stubs/installer/config.stub, resources/stubs/installer/env.stub, resources/views/system/installer/flash/message.blade.php
Migrate configs from the `config.php` into the `env.php` file, and then rename the `config.php` file.
Closes #1075
=> Migrate all configs into the env.php file #1075

resources/views/admin/airports/fields.blade.php, resources/views/admin/airports/table.blade.php
Added 100ll fields to the airport admin fields and table view
=> adds 100ll option to airport admin

app/Repositories/SubfleetRepository.php
Subfleet dropdown at flight search will look like `Boeing B737-800 WL | THY`
=> Add Airline ICAO to Subfleet selectBoxList

app/Exceptions/UserNotFound.php, app/Http/Controllers/Admin/UserController.php, app/Http/Controllers/Api/UserController.php, app/Models/Aircraft.php, app/Models/Enums/UserState.php, app/Models/User.php, app/Notifications/EventHandler.php, app/Services/PirepService.php, app/Services/UserService.php, resources/lang/en/user.php, resources/lang/es/user.php, resources/lang/it/user.php, resources/lang/pt-br/user.php, tests/AcarsTest.php, tests/UserTest.php
TODO:
- Block API calls for the user retrieval
- Delete open bids
- Option to hide deleted users/don't count in stats
Closes #1150
=> Delete the user in a GDPR compatible way

app/Http/Controllers/Frontend/HomeController.php, app/Widgets/LatestPilots.php
We should not display `Deleted User`s at Home Page and with Latest Pilots Widget.
=> Fixes For GDPR/Deleted Users

resources/views/admin/users/fields.blade.php
=> Disable autocomplete on admin email field

app/Http/Controllers/Frontend/AirportController.php
1. Inbound and Outbound flights were displaying all flights (active and inactive) , fixed to fetch only active flights.
2. Flash message and redirect to Dashboard was not working, instead we were getting 404 Not Found error.
=> Fix AirportController (Frontend)

resources/views/system/installer/install/steps/step3a-completed.blade.php
We do not have a config.php anymore, page should refer to env.php for base level configuration.
=> Fix Installer: Completed Blade

app/Http/Controllers/Admin/FlightController.php
Closes #1180 and #1156. But now the script isn't beeing loaded
=> Update Flight Controller to fix an issue

app/Database/factories/AirportFactory.php, app/Database/migrations/2021_05_21_141152_increase_icao_sizes.php, tests/AirportTest.php, tests/ApiTest.php
=> 5 char ICAO support #1052

resources/lang/en/flights.php, resources/lang/es/flights.php, resources/lang/it/flights.php, resources/lang/pt-br/flights.php, resources/views/layouts/default/flights/search.blade.php
Technically this was possible at backend/controller side but the search blade did not had the field to send data and do the search by code.
Also added 4 translations for the 'Code' word.
Closes #982
=> Add ability to search Flights by Code

app/Http/Controllers/Auth/LoginController.php, resources/views/admin/users/fields.blade.php
=> Remove the IP address from being recorded

app/Database/seeds/settings.yml, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Models/User.php, resources/views/admin/users/fields.blade.php
=> Add setting for recording IP address

app/Http/Controllers/Frontend/SimBriefController.php, app/Providers/RouteServiceProvider.php, app/Services/SimBriefService.php, config/phpvms.php, resources/views/layouts/default/flights/simbrief_briefing.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php
Changes aim to have the ability of editing generated SimBrief Flight Plans and re-downloading the latest one.
Closes #1226
=> Simbrief Edit & Download Latest OFP

app/Cron/Hourly/DeletePireps.php, app/Cron/Hourly/RemoveExpiredLiveFlights.php, app/Models/Enums/PirepState.php, app/Models/Enums/PirepStatus.php, resources/lang/de/pireps.php, resources/lang/en/pireps.php, resources/lang/es/pireps.php, resources/lang/it/pireps.php, resources/lang/pt-br/pireps.php
=> Add a 'paused' state

app/Contracts/ImportExport.php, app/Notifications/Messages/PirepStatusChanged.php, app/Services/ImportExport/FlightImporter.php, tests/ImporterTest.php
=> Check for blank values on import and omit them

app/Http/Controllers/Frontend/FlightController.php, app/Services/ModuleService.php, resources/views/layouts/default/flights/table.blade.php
The URI of `vmsacars:*` gets registered by ACARS on startup. This will only add "Launch in vmsACARS" if the VMSAcars plugin is installed and active
Closes #1272
=> Add ability to launch acars for flight/bid #1272

app/Http/Controllers/Frontend/FlightController.php, resources/views/layouts/default/flights/show.blade.php
Add missing $bid to flight/show so when needed **Load In Acars** button can be placed there too.
=> Bid check for flights/show

config/laravel-widgets.php
Title says it all ... Added web middleware to laravel-widgets config so the widget auto-reload / auto-refresh options can work with full functionality.
=> Add web middleware to laravel-widgets

app/Services/BidService.php
If present delete **unused** SimBrief OFP when the bid is being removed.
Tied to setting **SimBrief / Only For Bids**
=> Remove SimBrief with Bid

app/Services/GeoService.php
Instead of using the name twice provide more valuable information on popups (like location, lat/lon)
Also added location information to acars position reports' popup windows.
=> Improve Map features (GeoJson)

app/Models/Enums/AircraftStatus.php, resources/lang/de/aircraft.php, resources/lang/en/aircraft.php, resources/lang/es/aircraft.php, resources/lang/it/aircraft.php, resources/lang/pt-br/aircraft.php
Added the missing "Maintenance" status and all translations.
=> Maintenance Status for Aircraft

resources/views/admin/flights/search.blade.php, resources/views/admin/pireps/actions.blade.php, resources/views/admin/pireps/pirep_card.blade.php
1. Flight Search, used select2 with fixed grid layout
2. Pirep Actions, fixed button layout and added user_id before user name and made the name optional
=> Admin blade improvements

resources/views/admin/flights/search.blade.php
Somehow the form fields was acting weird and Airline dropdown was moving to another columns space. 
Error (visible also at Demo site);
Fixed it by re-assigning form classes along the grid, also moved the Find and Clear buttons to that row to save space.
=> Fix Admin / Flight Search (Blade)

app/Repositories/FlightRepository.php
=> Add callsign to flight search

app/Models/Flight.php, app/Models/Pirep.php
Both will use the same style for `ident` attribute like `JBU1900/C.HUM21/L.9`
=> Match Flight and Pirep ident attributes

resources/views/admin/pireps/pirep_card.blade.php
Removed `$pirep->airline->code`
=> Fix Admin pirep card | $pirep->ident usage

app/Notifications/Messages/PirepPrefiled.php, app/Notifications/Messages/PirepStatusChanged.php, app/Notifications/Messages/PirepSubmitted.php, resources/views/layouts/default/widgets/live_map.blade.php
3 for Discord notifications, 1 for default theme LiveMap Widget.
=> More `$pirep->ident` usage fixes

app/Http/Controllers/Auth/RegisterController.php
Only active fields should be passed to view during registration.
=> Only active fields should be passed to view during registration

app/Database/migrations/2021_11_27_132418_add_hub_to_aircraft.php, app/Http/Controllers/Admin/AircraftController.php, app/Models/Aircraft.php, app/Services/ImportExport/AircraftImporter.php, resources/views/admin/aircraft/fields.blade.php, resources/views/admin/aircraft/table.blade.php, resources/views/admin/subfleets/table.blade.php, tests/data/aircraft-update.csv, tests/data/aircraft.csv, tests/data/aircraft_empty_cols.csv
* Add ability to define a hub for an aircraft apart from it's subfleet.
* Update csv import/export capability of aircraft for new hub_id field
Closes #1357 
Closes #1258
=> Aircraft level Hub definitions

app/Models/Typerating.php, resources/views/admin/typeratings/fields.blade.php
Added `active` to fillable attributes of model
Fixed some visuals at admin > typeratings / fields.blade
=> Type Rating update

resources/views/layouts/default/widgets/weather.blade.php
Old blade was failing due to missing items in raw metar like `SVMC 031703Z AUTO NIL`
Also cleaned up tabs, converted indentations to spaces.
=> Fix Weather Widget blade

app/Http/Controllers/Frontend/PirepController.php
Check settings and filter aircraft list if needed.
If the user has no "current airport" or "home airport" info dropdown will be empty. (Possible during initial install for admin user)
=> Fix Aircraft dropdown not following settings (manual pirep)

docker-compose.yml
=> Fix docker image name

app/Repositories/UserRepository.php, resources/views/admin/users/index.blade.php, resources/views/admin/users/search.blade.php
Make `name` and `e-mail` based searches with `like` for easier administration.
Also update admin > users ; 
- index.blade.php ( proper state selection )
- search.blade.php ( remove dashed out old code )
=> Make name and e-mail based searches with like for easier administration.

app/Services/BidService.php
Dash out unnecessary check, let multiple users to bid on same flight according to settings.
Closes #1416
=> Allow bids on same flight by multiple users (as per settings)

resources/views/layouts/default/app.blade.php
Fix css and script_head yields.
Closes #1423
=> Laravel9 | Default Template > app.blade.php

app/Services/Finance/PirepFinanceService.php
=> Laravel9 | Fix undefined method

resources/views/admin/dashboard/index.blade.php, resources/views/admin/dashboard/news.blade.php, resources/views/layouts/default/widgets/latest_news.blade.php
Since acars is capable of showing them properly, I think web should allow admins to use WYSIWYG editor there too
=> HTML Formatted news

bin/cron
As suggested use 'phpvms:version' instead of just 'version'
=> Change cron command

app/Database/factories/AirportFactory.php, app/Database/migrations/2022_07_12_142108_add_notes_to_airports.php, app/Models/Airport.php, app/Services/ImportExport/AirportImporter.php, resources/views/admin/airports/fields.blade.php, resources/views/admin/airports/table.blade.php, resources/views/layouts/default/airports/show.blade.php, tests/ImporterTest.php, tests/data/airports.csv, tests/data/airports_special_chars.csv
Adds capability of having notes/remarks for airports, includes;
New database field
Airport Model change
CSV Import/Export capability for notes
Admin Airports list page change
Admin Airports edit page change
Default Template Airport show page change
Update tests for Airport Import
Closes #1466 (Feature Request)
=> Add "Notes" to Airports

resources/views/admin/flights/fares.blade.php, resources/views/admin/flights/fields.blade.php
Fixed one dead link, removed another one. Also changed load factor and variance fields to accept only numbers between 0-100.
Closes #1454
=> Fix dead links

app/Database/migrations/2022_08_20_213507_add_callsign_to_airlines.php, app/Models/Airline.php, resources/views/admin/airlines/fields.blade.php
Adds a new db field for radio telephony callsign for airlines.
Also adds necessary field to admin template.
=> Add Radio Callsign To Airlines

resources/views/layouts/default/flights/map.blade.php
Apply same color customization logic to flight maps
=> Apply color customization [Flight Map, Default Theme]

resources/views/admin/flights/fields.blade.php, resources/views/admin/flights/table.blade.php
Added "visible" field display to admin/flights/table and a checkbox to admin/flights/fields for controlling it easily from admin side (instead of going through database)
Enjoy :)
=> Flight Visibility Visuals

app/Services/ImportExport/FlightImporter.php, app/Services/ModuleService.php
Reverts nabeelio/phpvms#1487
Needs more testing, breaks current functionality
=> Revert "Bug fix #1414"

app/Database/migrations/2022_12_17_211036_add_callsign_to_users.php, app/Models/User.php, resources/views/admin/users/fields.blade.php, resources/views/admin/users/table.blade.php, resources/views/layouts/default/flights/simbrief_form.blade.php, resources/views/layouts/default/profile/index.blade.php
Provides;
- Migration file for a new database table field
- User Model change
- Admin interface changes (user list and user edit form)
- Profile page change
- SimBrief form change
Closes #1503
=> Add AlphaNumeric Callsign to users

app/Http/Controllers/Frontend/LanguageController.php, app/Http/Kernel.php, app/Http/Middleware/SetActiveLanguage.php, app/Providers/RouteServiceProvider.php, app/Providers/ViewComposerServiceProvider.php, config/languages.php, resources/views/layouts/default/nav.blade.php
This will allow each user to choose their own language, by default we will have the .env lang but it allows VAs with pilots from different countries to have the site in several languages.
=> Add user switch for lang

app/Http/Controllers/Admin/SettingsController.php, app/Http/Controllers/Frontend/LiveMapController.php, app/Providers/ViewComposerServiceProvider.php, app/Repositories/SubfleetRepository.php, app/Services/ModuleService.php, app/Support/Modules/DatabaseActivator.php, app/Widgets/LatestPilots.php, app/helpers.php, config/cache.php
=> Optimization

app/Http/Controllers/Frontend/FlightController.php
Tries to solve a big problem described in #1514 , basically OP needs to filter flights/schedule according to pirep settings (restrict by rank, restrict by type rating).
By OP's point of view, listing flights which a user can not fly and report is not needed and this change will accomplish that goal.
My point of view is different, I think we should have a separate setting to apply those filters to flights too. Because one VA may prefer showing the full schedule to its members to list what is available but not flyable by them yet due to restrictions.
Or maybe another solution; Like hiding bid/generate simbrief/load in acars buttons if that flight is not flyable by that pilot (this may need more development and sound more logical to me tbh)
Anyway, here is the basic and simple solution. In …
=> Filter flights/schedule according to rank/type ratings

config/logging.php
Allow days to keep logs to be defined via env.php, keep 3 as the default.
=> Update Log Config (Days)

app/Http/Resources/Fare.php
Do not send negative values (stops acars from starting flight), either send a positive value or zero to cover human errors.
=> Update Fare Resource

README.md
https://docs.phpvms.net/installation/installation was showing Page Not Found. Updated URL to https://docs.phpvms.net/installation
=> Updated wrong URL for installation page

app/Console/Commands/DevCommands.php, app/Console/Commands/PirepExport.php, app/Console/Commands/YamlExport.php, app/Console/Commands/YamlImport.php, app/Contracts/Command.php, app/Contracts/Repository.php, app/Http/Controllers/Api/PirepController.php, app/Http/Controllers/Frontend/LanguageController.php, app/Http/Controllers/Frontend/PirepController.php, app/Http/Controllers/Frontend/SimBriefController.php, app/Http/Controllers/System/InstallerController.php, app/Http/Controllers/System/UpdateController.php, app/Http/Requests/UpdateUserRequest.php, app/Models/Airport.php, app/Models/Pirep.php, app/Models/SimBriefXML.php, app/Providers/RouteServiceProvider.php, app/Services/AwardService.php, app/Services/FareService.php, app/Services/Finance/PirepFinanceService.php, app/Services/Installer/ConfigService.php, app/Services/Installer/SeederService.php, app/Services/Metar/AviationWeather.php, app/Services/UserService.php, app/Support/Metar.php, app/helpers.php, public/index.php, tests/AcarsTest.php, tests/ApiTest.php, tests/PIREPTest.php
=> Block read-only PIREP from being updated #1415

app/Events/ProcessAward.php, app/Listeners/AwardHandler.php, app/Services/PirepService.php, composer.json
=> Explicitly call the awards check #1418

app/Services/AirlineService.php, tests/AirlineTest.php
=> Only single journal should be initialized for an airline

app/Database/seeds/settings.yml
Adds necessary description fields and data to new settings to solve `production.ERROR: Undefined array key "description" {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined array key \"description\" at /app/Services/Installer/SeederService.php:266)` error.
Closes #1541
=> Update settings to fix Seed error

app/Http/Controllers/Auth/RegisterController.php
=> Fix RegisterController validator return type

app/Database/migrations/2023_06_24_204216_add_description_to_pirepfields.php, app/Models/PirepField.php, resources/views/admin/pirepfields/fields.blade.php, resources/views/admin/pirepfields/index.blade.php, resources/views/admin/pirepfields/show_fields.blade.php, resources/views/admin/pirepfields/table.blade.php, resources/views/layouts/default/pireps/custom_fields.blade.php
PR adds an optional description field to custom pirep fields, when provided that description is displayed during manual pirep creation.
Closes #1553
=> Description for Custom Pirep Fields

app/Models/Acars.php, app/Models/Aircraft.php, app/Models/Airline.php, app/Models/Airport.php, app/Models/Bid.php, app/Models/Expense.php, app/Models/Fare.php, app/Models/Flight.php, app/Models/FlightFieldValue.php, app/Models/Journal.php, app/Models/JournalTransaction.php, app/Models/News.php, app/Models/Pirep.php, app/Models/PirepComment.php, app/Models/PirepFare.php, app/Models/PirepFieldValue.php, app/Models/Rank.php, app/Models/SimBrief.php, app/Models/Subfleet.php, app/Models/Typerating.php, app/Models/User.php, app/Models/UserAward.php, app/Models/UserFieldValue.php
Added return types to current relationships
Added new relationships to Airport, Airline, Flight, Rank models
=> Model Updates (Relationships)

app/Http/Controllers/Api/PirepController.php
=> Return aircraft with pirep info in api

app/Http/Controllers/Admin/FlightController.php, app/Http/Controllers/Admin/PirepController.php, app/Http/Controllers/Api/AirportController.php, app/Http/Controllers/Frontend/FlightController.php, app/Http/Controllers/Frontend/PirepController.php, app/Http/Controllers/System/UpdateController.php, app/Http/Middleware/UpdatePending.php, app/Providers/RouteServiceProvider.php, app/Repositories/AirportRepository.php, app/Services/Installer/MigrationService.php, resources/views/admin/airports/table.blade.php, resources/views/admin/flights/create.blade.php, resources/views/admin/flights/fields.blade.php, resources/views/admin/flights/scripts.blade.php, resources/views/admin/pireps/fields.blade.php, resources/views/admin/pireps/scripts.blade.php, resources/views/admin/scripts/airport_search.blade.php, resources/views/layouts/default/app.blade.php, resources/views/layouts/default/flights/scripts.blade.php, resources/views/layouts/default/flights/search.blade.php, resources/views/layouts/default/pireps/fields.blade.php, resources/views/layouts/default/pireps/scripts.blade.php, resources/views/layouts/default/scripts/airport_search.blade.php, tests/AirportTest.php
=> Search for airports by xhr request

app/Repositories/AirportRepository.php, resources/views/admin/scripts/airport_search.blade.php, resources/views/layouts/default/scripts/airport_search.blade.php
=> Fix airport xhr request search

app/Http/Resources/Airport.php
Removes code preventing look up of airports
=> Airport lookup

app/Models/Airline.php
Fixed key conventions and relationship types to get proper results.
=> Airline Model fix

app/Http/Controllers/Admin/RankController.php
=> Bug fix #1275

resources/views/layouts/default/flights/table.blade.php
Closes #1600 
Simple fix, checking the existence of the array first, then proceeding.
=> Fix flights page error

resources/views/layouts/default/flights/search.blade.php
=> Improved UX of Search Labels being associated to the correct inputs.

app/Services/ModuleService.php
=> fixModuleMigration

app/Services/LegacyImporter/AirportImporter.php
=> Add the additional airport import fields

app/Database/migrations/2017_06_21_165410_create_ranks_table.php, app/Database/seeds/prod/ranks.yml, tests/ImporterTest.php, tests/data/subfleets.csv
=> Fix Ranks Seeder

app/Http/Controllers/Api/StatusController.php, app/Providers/RouteServiceProvider.php
=> Add api info page

app/Services/Metar/AviationWeather.php
Closes #1639 
Change to new server url with backwards compatible output.
We should consider implementing the new API for all WX data instead of using old dataserver compatibility option ;)
=> Update Aviation WX Services

app/Http/Controllers/Admin/RankController.php, resources/views/admin/ranks/subfleets.blade.php
Close #1534 
I had to remove the placeholder because it was added as a selected value of the input (I don't know why). Instead I added a label.
=> Add the ability to add several subfleets at once to a rank

resources/views/admin/pireps/fields.blade.php
Allows admin/staff to edit flight times of accepted pireps.
Closes #1645
=> Update Admin > Pirep > fields.blade.php

app/Services/LegacyImporter/PirepImporter.php
PR aims to get valuable data to proper fields in v7 database during v5/legacy imports.
* Landing Rate
* Fuel Used
* Submit Date
Closes #1652 
Thanks to @ProAviaAZ for providing v5 data and detailed support for contents.
=> Legacy Pirep Importer > Add missing fields

app/Database/seeds/settings.yml, app/Events/PirepDiverted.php, app/Listeners/DiversionHandler.php, app/Notifications/Messages/Broadcast/PirepDiverted.php, app/Providers/EventServiceProvider.php, app/Services/FlightService.php, app/Services/PirepService.php
Close #1309 
Close #1572 
From what I have tested it works quite well.
Do you think we should add tests for this ? 
Perhaps we should change the text of the `notifications.discord_pirep_diverted` setting because I don't have the impression that what I wrote is very English...
@FatihKoz does this look like what you imagined ?
=> Handle Diversion

app/Listeners/TLDUpdater.php, app/Providers/EventServiceProvider.php, config/phpvms.php
=> Update TLD list via cron

app/Services/LegacyImporter/UserImport.php
Allow importing transfer hours from legacy to v7
Closes #1667
=> Update Legacy User Import

app/Http/Controllers/Admin/AircraftController.php, app/Http/Controllers/Admin/FareController.php, app/Http/Controllers/Admin/SubfleetController.php
Closes #1669 
And one more Subfleet restore related issue not reported here.
=> Fix Admin Controllers (for TrashBin)

app/Services/ImportExport/FlightImporter.php
To fix notes/remarks field not being imported bug reported via Discord
=> Update Flight Importer

app/Services/FlightService.php
It's better when the pilot who booked an aircraft can see it :)
=> Fix filterSubfleets for booked aircrafts

resources/views/admin/pages/fields.blade.php
Cancel Button Redirected to Roles, instead of Pages. Fixed.
=> Fixed Pages Cancel Button Link & Changed CKEditor Options

app/Http/Controllers/Admin/FlightController.php, app/Models/Flight.php, resources/views/admin/flights/index.blade.php, resources/views/admin/flights/table.blade.php
- Controller change to allow sortable results
- Model update to allow new fields in sortable results
- flights/table change for new fields and sortable results
_(Subfleets assigned, Route and Notes are displayed with an icon with mouse hover to save space)_
=> Sortable Admin Flights List

app/Http/Controllers/Admin/AwardController.php, app/Models/Award.php, app/Models/UserAward.php, resources/views/admin/awards/edit.blade.php, resources/views/admin/awards/owners_table.blade.php, resources/views/admin/awards/table.blade.php
Sortable results at awards index with user counts, also displays the owners of awards (sortable) at award edit page.
=> Sortable Admin Awards (with User Details)

resources/views/admin/pireps/fields.blade.php
Provide details from the flight and/or from plan (simbrief, pln etc) and allow admins to edit more details of pireps received.
=> Admin > Pirep Edit (More Details)

app/Http/Controllers/Admin/MaintenanceController.php
Use Laravel's Facade instead of exec function. I don't know why but some people don't have the exec function.
=> Fix cache clear

app/Database/seeds/.gitignore, app/Support/Database.php, app/Support/Modules/DatabaseActivator.php, tests/DatabaseTest.php, tests/TestCase.php, tests/data/.gitignore, tests/data/seed.yml
Ignore parameter was being skipped
=> Fix bug in seeder with missing optional param

composer.json, composer.lock
=> Postmark Mailer Support

app/Database/migrations/2023_12_15_154815_create_user_oauth_tokens_table.php, app/Http/Controllers/Auth/OAuthController.php, app/Models/User.php, app/Models/UserOAuthToken.php, app/Providers/RouteServiceProvider.php, config/services.php, resources/lang/de/auth.php, resources/lang/en/auth.php, resources/lang/es-es/auth.php, resources/lang/fr/auth.php, resources/lang/it/auth.php, resources/lang/pt-br/auth.php, resources/views/layouts/default/auth/login.blade.php, resources/views/layouts/default/auth/register.blade.php, resources/views/layouts/default/profile/index.blade.php
I need your review on the db structure.
I don't know if I should automatically verify the email as part of an oauth registration (considering that the provider has already done it) which would allow, in the event of auto approval, to redirect directly to the edit profile page.
Some providers like discord return nickname in the name field so by default the name of a user is their discord nickname...
=> Login with discord

app/Http/Controllers/Frontend/PirepController.php, app/Http/Middleware/InstalledCheck.php, resources/views/system/installer/errors/already-installed.blade.php
The condition used previously was wrong since there is also step 3 which must have been done for the installation to be completed
=> Fix InstalledCheck Middleware (hotfix)

app/Notifications/Messages/NewsAdded.php
Aims to close #1741 
Needs testing and discussion about initial implementation before merge.
=> Disable toDiscordChannel()

app/Http/Controllers/Frontend/PirepController.php, app/Notifications/Messages/Broadcast/NewsAdded.php, composer.json, composer.lock
Example:
```html
<h1>Sample h1</h1>
<h2>Sample h2</h2>
<p>This is a paragraph</p>
<ul>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
```
becomes
=> Use Markdown in discord notifications

app/Http/Controllers/Frontend/PirepController.php, resources/views/admin/pireps/actions.blade.php
Fix actions background color on hover
Before:
After:
=> Fix CSS in Admin Pireps Table

composer.json, composer.lock
Dependencies will be there and ready in builds if someone needs to use them.
=> S3 and SFTP filesystem support

app/Database/seeds/settings.yml, app/Notifications/NotificationEventsHandler.php
=> Add setting for Discord PirepFiled Notifications

resources/views/admin/pireps/fields.blade.php
Field values should match the labels and internal units should be displayed for admins/staff.
_Blade Change Only, html form tags used_
=> Admin Theme > Internal Units Fix (Pirep Fields)

app/Services/ImportExport/FareImporter.php, tests/ImporterTest.php, tests/data/fares.csv
Closes #1792 
0 stands for PASSENGER
1 stands for CARGO
see here:
https://github.com/nabeelio/phpvms/blob/d774ffedf7fa69287cf10f3cf77bea94cc28b13e/app/Models/Enums/FareType.php#L9-L10
=> Add FareType to Import/Export

app/Models/User.php
Allow `$user->award->pivot` to have the timestamps
=> Update User Model

resources/views/admin/airports/index.blade.php
Without the change it will not be possible to live sort and use pagination.
=> Admin > Fix Airport Pagination

app/Notifications/Messages/Broadcast/PirepStatusChanged.php
Hello, In the last few days I implemented this option in my VA and my pilots liked it, that is why I am sending this change for other VA.
=> Add Landing rate to discord broadcast

.github/scripts/version.sh, .github/workflows/build.yml, GitVersion.yml, app/Database/seeds/dev/in_progress.yml
=> Use GitVersion for versioning

app/Services/BidService.php
For details on the issue see: https://discord.com/channels/332920618729340929/780945843654098944/1281796927197024332
=> Fix findBidsForUser default params

app/Http/Controllers/Frontend/CreditsController.php, app/Providers/RouteServiceProvider.php, resources/views/layouts/default/credits.blade.php
This is a simple example about how to read `module.json` file and provide some credits.
_Most of the "Module" facade attributes are protected, thus a direct reading was required._
**Should not be merged directly, this is still a maturing idea**
Closes #1867 when finished 😺
=> Credits (Feature Request)

resources/views/admin/aircraft/fields.blade.php
Fix for the `undefined variable` issue being observed while creating a new aircraft.
_Previous failsafe was not enough due to mass casting and local unit conversion, isset() is required_
=> New Aircraft creation issue fix

app/Services/PirepService.php
We need to check correct setting (and preferably we should name it in a more human readable form in the code)
=> Fix Diversion Handling (Repositioning Flight Creation)

resources/views/admin/pireps/fields.blade.php
=> Update Admin > Pireps > fields.blade.php

resources/views/layouts/seven/widgets/weather.blade.php
=> Fix WX Widget in Seven Theme

resources/views/layouts/seven/credits.blade.php
Closes #1935 
Thanks @PaintSplasher for his contribution, nice catch there.
=> Credits blade for seven theme

app/Database/migrations/2025_01_13_003704_create_phpvms_table.php
FK checks may or may not have table prefixes...
=> Update the full table migration for FKs

Makefile, README.md
1. Update requirements
2. Update default php version for docker install
=> [8.x] Update Readme

resources/views/filament/system/legacy_importer_details.blade.php, resources/views/filament/system/migrations_details.blade.php
=> [8.x] Add "Processing, please wait" message during migrations in updater and installer

resources/views/layouts/seven/auth/register.blade.php
Fix hcaptcha sitekey tag on the registration form.
Apply for both versions
Fixes #1970
@arthurpar06, @FatihKoz, should we have the hcaptcha on the login form as well?
=> [v7.x/ v8.x] fix: fix hcaptcha sitekey tag

.github/workflows/lint.yml
=> [7.x] Fix pint workflow

app/Http/Controllers/Frontend/PirepController.php, resources/views/notifications/mail/admin/pirep/submitted.blade.php
Fix some outdated admin links that should have been migrated to filament links
=> [8.x] Fix admin links

app/Models/Aircraft.php
This PR addresses an issue that occurs when trying to create a new aircraft in filament.
=> [8.x] Fix Aircraft model

.github/workflows/build.yml, .github/workflows/release.yml
This PR enables building assets directly in CI. However, it needs to be tested after merging because I can't test it myself, as I can't run workflows on my fork.
Additionally, should we remove all the built assets from git? I think we should, but I wanted to check with you before proceeding. If you agree, I'll remove them, and then this PR will be ready to merge.
=> [8.x] Build assets in CI

app/Filament/Widgets/AirlineFinanceChart.php, app/Filament/Widgets/AirlineFinanceTable.php
Avoid attempting to create a Money instance from null
=> [8.x] Add some failsafes to the finances page

app/Filament/Resources/Airports/Actions/LookupAction.php
The country code should be lowercase
=> fix: LookupAction

app/Filament/Resources/Airlines/Tables/AirlinesTable.php
fix the leading / when no iata code is set and the searchable columns
=> fix: AirlinesTable

app/Filament/Resources/Subfleets/RelationManagers/AircraftRelationManager.php
=> [8.x] feat(aircraft): re-add import/export actions
